require "Items/ProceduralDistributions"
-- VN125muffler
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.VN125muffler");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.VN125muffler");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.VN125muffler");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- VN125oldTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.VN125oldTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.VN125oldTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.VN125oldTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.VN125oldTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- VN125normalTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.VN125normalTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.VN125normalTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.VN125normalTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- VN125modernTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.VN125modernTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.VN125modernTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.VN125modernTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- VN125seat
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.VN125seat");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.VN125seat");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.VN125seat");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);