require 'Items/ProceduralDistributions'

    -- Base.ATAProtectionWheelsChain
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfTools"].junk.items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["MechanicShelfWheels"].items, 1);
    table.insert(ProceduralDistributions.list["CrateMetalwork"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["CrateMetalwork"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Base.ATAProtectionWheelsChain");
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
    
    -- Base.ATARoofLightItem
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["CrateMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["GarageMechanics"].items, 1);
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].items, 1);
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, "Base.ATARoofLightItem");
    table.insert(ProceduralDistributions.list["MechanicShelfElectric"].junk.items, 1);
