require "Items/Distributions"
require "Items/ItemPicker"
require "Items/ProceduralDistributions"
require "Vehicles/VehicleDistributions"

-- Ammo Can 50

table.insert(ProceduralDistributions["list"]["ArmyStorageAmmunition"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["ArmyStorageAmmunition"].items, 5.0)
table.insert(ProceduralDistributions["list"]["ArmyStorageGuns"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["ArmyStorageGuns"].items, 4.0)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.05)
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, 0.05)
table.insert(ProceduralDistributions["list"]["PawnShopGunsSpecial"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["PawnShopGunsSpecial"].items, 2.0)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 0.05)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 0.05)
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "newcontainers.ammocan50")
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 0.05)

-- Ammo Can 30

table.insert(ProceduralDistributions["list"]["ArmyStorageAmmunition"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["ArmyStorageAmmunition"].items, 5.0)
table.insert(ProceduralDistributions["list"]["ArmyStorageGuns"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["ArmyStorageGuns"].items, 4.0)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["DrugLabGuns"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.05)
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["LockerArmyBedroom"].items, 0.05)
table.insert(ProceduralDistributions["list"]["PawnShopGunsSpecial"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["PawnShopGunsSpecial"].items, 2.0)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 0.05)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 0.05)
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, "newcontainers.ammocan30")
table.insert(ProceduralDistributions["list"]["WardrobeRedneck"].items, 0.05)

--Basket

table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["BathroomCounterNoMeds"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["CrateTailoring"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GigamartBedding"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["GigamartBedding"].items, 4.0)
table.insert(ProceduralDistributions["list"]["Homesteading"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["Homesteading"].items, 1.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 2.0)
table.insert(ProceduralDistributions["list"]["LaundryCleaning"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["LaundryCleaning"].items, 2.0)
table.insert(ProceduralDistributions["list"]["SewingStoreTools"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["SewingStoreTools"].items, 4.0)
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, "newcontainers.basket")
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, 1.0)

-- Canvas Tote 		

table.insert(ProceduralDistributions["list"]["BookstoreBags"].items, "newcontainers.canvastote")
table.insert(ProceduralDistributions["list"]["BookstoreBags"].items, 10.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.canvastote")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["StoreCounterBagsFancy"].items, "newcontainers.canvastote")
table.insert(ProceduralDistributions["list"]["StoreCounterBagsFancy"].items, 5.0)

-- Cardboard Box Large

table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinBar"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["BinBar"].items, 1.0)
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, 10.0)
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JunkBin"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["JunkBin"].items, 8.0)
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, 10.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 0.5)
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 4.0)
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 20.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 10.0)
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 0.1)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 0.1)
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, 2.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, "newcontainers.cardboard_large")
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, 2.0)
table.insert(VehicleDistributions["PostalTruckBed"].items, "newcontainers.cardboard_large")
table.insert(VehicleDistributions["PostalTruckBed"].items, 4.0)

-- Cardboard Box Medium

table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinBar"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["BinBar"].items, 1.0)
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, 10.0)
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JunkBin"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["JunkBin"].items, 8.0)
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, 10.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 0.5)
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 4.0)
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 20.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 10.0)
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 0.1)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 0.1)
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, 2.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, "newcontainers.cardboard_medium")
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, 2.0)
table.insert(VehicleDistributions["PostalTruckBed"].items, "newcontainers.cardboard_medium")
table.insert(VehicleDistributions["PostalTruckBed"].items, 4.0)

-- Cardboard Box Small

table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["BarCounterMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinBar"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["BinBar"].items, 1.0)
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["DinerBackRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["FishChipsKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["GigamartSchool"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["GroceryStorageCrate1"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ItalianKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["JanitorMisc"].items, 10.0)
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["JaysKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JunkBin"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["JunkBin"].items, 8.0)
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, 10.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 0.5)
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["MechanicShelfMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 4.0)
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["PizzaKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 20.0)
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["PostOfficeBoxes"].items, 10.0)
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["RandomFiller"].items, 0.1)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 0.1)
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, 2.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["StoreKitchenButcher"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, "newcontainers.cardboard_small")
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, 2.0)
table.insert(VehicleDistributions["PostalTruckBed"].items, "newcontainers.cardboard_small")
table.insert(VehicleDistributions["PostalTruckBed"].items, 4.0)

-- Coffee Can 		

table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, "newcontainers.coffeecan")
table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, "newcontainers.coffeecan")
table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, 2.0)
table.insert(ProceduralDistributions["list"]["KitchenBreakfast"].items, "newcontainers.coffeecan")
table.insert(ProceduralDistributions["list"]["KitchenBreakfast"].items, 1.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenCafe"].items, "newcontainers.coffeecan")
table.insert(ProceduralDistributions["list"]["StoreKitchenCafe"].items, 2.0)

-- Coffee Can Open

table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.coffeecan_open")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.4)
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "newcontainers.coffeecan_open")
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 2.0)



-- Cookie Jar 		

table.insert(ProceduralDistributions["list"]["BakeryMisc"].items, "newcontainers.cookiejar")
table.insert(ProceduralDistributions["list"]["BakeryMisc"].items, 5.0)
table.insert(ProceduralDistributions["list"]["GigamartPots"].items, "newcontainers.cookiejar")
table.insert(ProceduralDistributions["list"]["GigamartPots"].items, 4.0)
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, "newcontainers.cookiejar")
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, 1.0)
table.insert(ProceduralDistributions["list"]["KitchenPots"].items, "newcontainers.cookiejar")
table.insert(ProceduralDistributions["list"]["KitchenPots"].items, 1.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, "newcontainers.cookiejar")
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, 4.0)

-- Cutlery Roll

table.insert(ProceduralDistributions["list"]["BurgerKitchenButcher"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["BurgerKitchenButcher"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ButcherTools"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["ButcherTools"].items, 4.0)
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["ChineseKitchenButcher"].items, 3.0)
table.insert(ProceduralDistributions["list"]["ChineseKitchenCutlery"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["ChineseKitchenCutlery"].items, 1.0)
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["MexicanKitchenButcher"].items, 1.0)
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["SeafoodKitchenButcher"].items, 1.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenCutlery"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["StoreKitchenCutlery"].items, 1.0)
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, "newcontainers.cutleryroll")
table.insert(ProceduralDistributions["list"]["WesternKitchenButcher"].items, 1.0)

-- Donut Box		

table.insert(ProceduralDistributions["list"]["BakeryDoughnuts"].items, "newcontainers.donutbox")
table.insert(ProceduralDistributions["list"]["BakeryDoughnuts"].items, 5.0)
table.insert(ProceduralDistributions["list"]["BakeryKitchenBaking"].items, "newcontainers.donutbox")
table.insert(ProceduralDistributions["list"]["BakeryKitchenBaking"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BakeryMisc"].items, "newcontainers.donutbox")
table.insert(ProceduralDistributions["list"]["BakeryMisc"].items, 5.0)
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.donutbox")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.donutbox")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)

-- Fake Rock

table.insert(ProceduralDistributions["list"]["CrateFarming"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.1)
table.insert(ProceduralDistributions["list"]["GarageTools"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, 2.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, "newcontainers.fakerock")
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, 2.0)

-- Foraging Basket

table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.5)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, 1.0)
table.insert(ProceduralDistributions["list"]["Homesteading"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["Homesteading"].items, 2.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, "newcontainers.basket_forage")
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, 4.0)

-- Forage Pouch

table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["CrateFarming"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["GardenStoreMisc"].items, 2.0)
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["GigamartFarming"].items, 2.0)
table.insert(ProceduralDistributions["list"]["Homesteading"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["Homesteading"].items, 4.0)
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["KitchenRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, "newcontainers.foragingpouch_front")
table.insert(ProceduralDistributions["list"]["ToolStoreFarming"].items, 8.0)

-- Jewelry Box

table.insert(ProceduralDistributions["list"]["Antiques"].items, "newcontainers.jewelrybox")
table.insert(ProceduralDistributions["list"]["Antiques"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "newcontainers.jewelrybox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.5)
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "newcontainers.jewelrybox")
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.5)
table.insert(ProceduralDistributions["list"]["DepartmentStoreJewelry"].items, "newcontainers.jewelrybox")
table.insert(ProceduralDistributions["list"]["DepartmentStoreJewelry"].items, 2.0)
table.insert(ProceduralDistributions["list"]["JewelryStorageAll"].items, "newcontainers.jewelrybox")
table.insert(ProceduralDistributions["list"]["JewelryStorageAll"].items, 2.0)

--Jug

table.insert(ProceduralDistributions["list"]["ArmyStorageMedical"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["ArmyStorageMedical"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["ArmySurplusMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 5.0)
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.01)
table.insert(ProceduralDistributions["list"]["Homesteading"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["Homesteading"].items, 2.0)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.jugempty")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 1.0)

-- Kindling Box		

table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "newcontainers.kindlingbox")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.kindlingbox")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["Homesteading"].items, "newcontainers.kindlingbox")
table.insert(ProceduralDistributions["list"]["Homesteading"].items, 1.0)

-- Lock Box

table.insert(ProceduralDistributions["list"]["Antiques"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["Antiques"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.5)
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.5)
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["DeskGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 0.1)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, 1.0)
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, "newcontainers.lockbox")
table.insert(ProceduralDistributions["list"]["PoliceDesk"].items, 1.0)

-- Piggy Bank

table.insert(ProceduralDistributions["list"]["Antiques"].items, "newcontainers.piggybank")
table.insert(ProceduralDistributions["list"]["Antiques"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "newcontainers.piggybank")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 0.5)
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "newcontainers.piggybank")
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.5)
table.insert(ProceduralDistributions["list"]["WardrobeChild"].items, "newcontainers.piggybank")
table.insert(ProceduralDistributions["list"]["WardrobeChild"].items, 0.5)



-- Pizza Box

table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.pizzabox")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.pizzabox")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)

-- Pizza Box PW

table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["FreezerRich"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["FreezerRich"].items, 2.0)
table.insert(ProceduralDistributions["list"]["FridgeOffice"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["FridgeOffice"].items, 4.0)
table.insert(ProceduralDistributions["list"]["MotelFridge"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["MotelFridge"].items, 6.0)
table.insert(ProceduralDistributions["list"]["PizzaKitchenBaking"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["PizzaKitchenBaking"].items, 5.0)
table.insert(ProceduralDistributions["list"]["PizzaKitchenFridge"].items, "newcontainers.pizzaboxpw")
table.insert(ProceduralDistributions["list"]["PizzaKitchenFridge"].items, 5.0)

-- Plastic Tote	Lg

table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "newcontainers.plastictote_large")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 0.1)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.plastictote_large")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 2.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.plastictote_large")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.1)

-- Plastic Tote Md

table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "newcontainers.plastictote_medium")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 0.5)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.plastictote_medium")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 4.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.plastictote_medium")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.5)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.plastictote_medium")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 1.0)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.plastictote_medium")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 2.0)

-- Plastic Tote Sm

table.insert(ProceduralDistributions["list"]["CrateCamping"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["CrateCamping"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 8.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, 0.5)
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, 0.5)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.plastictote_small")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 4.0)

-- Roadside Kit

table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, "newcontainers.roadsidekit")
table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, 4.0)
table.insert(VehicleDistributions["TrunkStandard"].items, "newcontainers.roadsidekit")
table.insert(VehicleDistributions["TrunkStandard"].items, 0.5)
table.insert(VehicleDistributions["TrunkHeavy"].items, "newcontainers.roadsidekit")
table.insert(VehicleDistributions["TrunkHeavy"].items, 0.5)
table.insert(VehicleDistributions["TrunkSports"].items, "newcontainers.roadsidekit")
table.insert(VehicleDistributions["TrunkSports"].items, 0.5)
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, "newcontainers.roadsidekit")
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, 0.5)

-- Shoe Box

table.insert(ProceduralDistributions["list"]["BinDumpster"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["BinDumpster"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["BinGeneric"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BowlingAlleyShoes"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["BowlingAlleyShoes"].items, 5.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 10.0)
table.insert(ProceduralDistributions["list"]["ClothingStorageFootwear"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["ClothingStorageFootwear"].items, 4.0)
table.insert(ProceduralDistributions["list"]["CrateFootwearRandom"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["CrateFootwearRandom"].items, 1.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 1.0)
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["DrugShackMisc"].items, 4.0)
table.insert(ProceduralDistributions["list"]["JunkBin"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["JunkBin"].items, 8.0)
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["JunkHoard"].items, 10.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 0.5)
table.insert(ProceduralDistributions["list"]["ToolStoreFootwear"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["ToolStoreFootwear"].items, 4.0)
table.insert(ProceduralDistributions["list"]["WardrobeChild"].items, "newcontainers.shoebox")
table.insert(ProceduralDistributions["list"]["WardrobeChild"].items, 0.1)

-- Shopping Basket

table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, "newcontainers.shoppingbasket")
table.insert(ProceduralDistributions["list"]["StoreCounterBags"].items, 25.0)
table.insert(ProceduralDistributions["list"]["StoreCounterBagsFancy"].items, "newcontainers.shoppingbasket")
table.insert(ProceduralDistributions["list"]["StoreCounterBagsFancy"].items, 25.0)

--Spice Rack

table.insert(ProceduralDistributions["list"]["GigamartPots"].items, "newcontainers.spicerack")
table.insert(ProceduralDistributions["list"]["GigamartPots"].items, 4.0)
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, "newcontainers.spicerack")
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, 1.0)
table.insert(ProceduralDistributions["list"]["KitchenPots"].items, "newcontainers.spicerack")
table.insert(ProceduralDistributions["list"]["KitchenPots"].items, 1.0)
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, "newcontainers.spicerack")
table.insert(ProceduralDistributions["list"]["StoreKitchenPots"].items, 4.0)
table.insert(ProceduralDistributions["list"]["StoreShelfSpices"].items, "newcontainers.spicerack")
table.insert(ProceduralDistributions["list"]["StoreShelfSpices"].items, 5.0)

-- Tackle Box

table.insert(ProceduralDistributions["list"]["CrateFishing"].items, "newcontainers.tacklebox")
table.insert(ProceduralDistributions["list"]["CrateFishing"].items, 10.0)
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "newcontainers.tacklebox")
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.05)
table.insert(ProceduralDistributions["list"]["FishingStoreGear"].items, "newcontainers.tacklebox")
table.insert(ProceduralDistributions["list"]["FishingStoreGear"].items, 10.0)
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, "newcontainers.tacklebox")
table.insert(ProceduralDistributions["list"]["SurvivalGear"].items, 2.0)
table.insert(VehicleDistributions["FishermanTruckBed"].items, "newcontainers.tacklebox")
table.insert(VehicleDistributions["FishermanTruckBed"].items, 5.0)

-- Tissue Box

table.insert(ProceduralDistributions["list"]["ArmyStorageMedical"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ArmyStorageMedical"].items, 8.0)
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, 10.0)
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 4.0)
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["BedroomDresser"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ChangeroomCounters"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ChangeroomCounters"].items, 10.0)
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ClassroomMisc"].items, 1.0)
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, 2.0)
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 8.0)
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["CrateOfficeSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["LibraryCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 2.0)
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["OfficeCounter"].items, 8.0)
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["OfficeDesk"].items, 4.0)
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["OfficeDeskHome"].items, 8.0)
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["OfficeShelfSupplies"].items, 10.0)
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["OtherGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 10.0)
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["PostOfficeSupplies"].items, 8.0)
table.insert(ProceduralDistributions["list"]["SafehouseMedical"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["SafehouseMedical"].items, 5.0)
table.insert(ProceduralDistributions["list"]["ScienceMisc"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ScienceMisc"].items, 10.0)
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 1.0)
table.insert(ProceduralDistributions["list"]["VacationStuff"].items, "newcontainers.tissuebox")
table.insert(ProceduralDistributions["list"]["VacationStuff"].items, 2.0)

-- Travel Kit		


table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, "newcontainers.travelkit")
table.insert(ProceduralDistributions["list"]["BathroomCabinet"].items, 5.0)
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, "newcontainers.travelkit")
table.insert(ProceduralDistributions["list"]["BathroomCounter"].items, 2.0)
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, "newcontainers.travelkit")
table.insert(ProceduralDistributions["list"]["BathroomShelf"].items, 2.0)
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, "newcontainers.travelkit")
table.insert(ProceduralDistributions["list"]["PharmacyCosmetics"].items, 5.0)
table.insert(ProceduralDistributions["list"]["VacationStuff"].items, "newcontainers.travelkit")
table.insert(ProceduralDistributions["list"]["VacationStuff"].items, 4.0)
table.insert(VehicleDistributions["GloveBox"].items, "newcontainers.travelkit")
table.insert(VehicleDistributions["GloveBox"].items, 1.0)
table.insert(VehicleDistributions["ConstructionWorkerGloveBox"].items, "newcontainers.travelkit")
table.insert(VehicleDistributions["ConstructionWorkerGloveBox"].items, 1.0)
table.insert(VehicleDistributions["RangerGloveBox"].items, "newcontainers.travelkit")
table.insert(VehicleDistributions["RangerGloveBox"].items, 1.0)
table.insert(VehicleDistributions["HunterGloveBox"].items, "newcontainers.travelkit")
table.insert(VehicleDistributions["HunterGloveBox"].items, 1.0)
table.insert(VehicleDistributions["SurvivalistGlovebox"].items, "newcontainers.travelkit")
table.insert(VehicleDistributions["SurvivalistGlovebox"].items, 1.0)

-- Trunk Organizer

table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, "newcontainers.trunkorganizer")
table.insert(ProceduralDistributions["list"]["CarSupplyTools"].items, 4.0)
table.insert(VehicleDistributions["TrunkStandard"].items, "newcontainers.trunkorganizer")
table.insert(VehicleDistributions["TrunkStandard"].items, 1.0)
table.insert(VehicleDistributions["TrunkHeavy"].items, "newcontainers.trunkorganizer")
table.insert(VehicleDistributions["TrunkHeavy"].items, 1.0)
table.insert(VehicleDistributions["TrunkSports"].items, "newcontainers.trunkorganizer")
table.insert(VehicleDistributions["TrunkSports"].items, 1.0)
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, "newcontainers.trunkorganizer")
table.insert(VehicleDistributions["SurvivalistTruckBed"].items, 1.0)
