require "Items/ProceduralDistributions"
-- DodgeRTtire3
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.DodgeRTtire3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.DodgeRTtire3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.DodgeRTtire3");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.DodgeRTtire3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.DodgeRTtire3");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- DG70FrontBumperC
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.DG70FrontBumperC");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.DG70FrontBumperC");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.DG70FrontBumperC");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.DG70FrontBumperC");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.DG70FrontBumperC");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- DG70RearBumperC
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.DG70RearBumperC");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.DG70RearBumperC");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.DG70RearBumperC");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.DG70RearBumperC");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.DG70RearBumperC");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- DG70Spoiler0
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.DG70Spoiler0");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.DG70Spoiler0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.DG70Spoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.DG70Spoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.DG70Spoiler0");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- DG70Spoiler1
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.DG70Spoiler1");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.DG70Spoiler1");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.DG70Spoiler1");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.DG70Spoiler1");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.DG70Spoiler1");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);