-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["ivery_christmas_0"] = {{ name = "other", tiles = {"ivery_christmas_14",
"ivery_christmas_15"} }}
overlayMap["ivery_community_01_0"] = {{ name = "other", tiles = {"ivery_community_01_8",
"ivery_community_01_8"} }}
overlayMap["ivery_community_01_1"] = {{ name = "other", tiles = {"ivery_community_01_9",
"ivery_community_01_9"} }}
overlayMap["ivery_community_01_2"] = {{ name = "other", tiles = {"ivery_community_01_10",
"ivery_community_01_10"} }}
overlayMap["ivery_community_01_3"] = {{ name = "other", tiles = {"ivery_community_01_11",
"ivery_community_01_11"} }}
overlayMap["ivery_community_01_4"] = {{ name = "other", tiles = {"ivery_community_01_12",
"ivery_community_01_12"} }}
overlayMap["ivery_community_01_5"] = {{ name = "other", tiles = {"ivery_community_01_13",
"ivery_community_01_13"} }}
overlayMap["ivery_community_01_6"] = {{ name = "other", tiles = {"ivery_community_01_14",
"ivery_community_01_14"} }}
overlayMap["ivery_community_01_7"] = {{ name = "other", tiles = {"ivery_community_01_15",
"ivery_community_01_15"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
