EggonsMU.Containers = {
    bin = "bin",
    counter = "counter",
    crate = "crate",
    campfire = "campfire",
    cashregister = "cashregister",
    clothingdryer = "clothingdryer",
    clothingrack = "clothingrack",
    clothingwasher = "clothingwasher",
    desk = "desk",
    dishescabinet = "dishescabinet",
    displaycase = "displaycase", -- in cafe, gun store - lada wystawowa
    displaycasebakery = "displaycasebakery",
    dresser = "dresser",
    filingcabinet = "filingcabinet",
    freezer = "freezer",
    fridge = "fridge",
    grocerstand = "grocerstand",
    inventoryfemale = "inventoryfemale",
    inventorymale = "inventorymale",
    locker = "locker",
    medicine = "medicine", -- hanging in bathroom ?
    metal_shelves = "metal_shelves",
    microwave = "microwave",
    officedrawers = "officedrawers",
    other = "other",
    overhead = "overhead", -- kitchens. Hanging counter
    postbox = "postbox",
    restaurantdisplay = "restaurantdisplay",
    shelves = "shelves",
    shelvesmag = "shelvesmag", -- mag racks in gas stations?
    sidetable = "sidetable",
    stove = "stove",
    vendingpop = "vendingpop",
    vendingsnack = "vendingsnack",
    wardrobe = "wardrobe"
}
