require "Items/ProceduralDistributions"
-- ZNL50muffler
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50muffler");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ZNL50muffler");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ZNL50muffler");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- ZNL50oldTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50oldTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ZNL50oldTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ZNL50oldTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.ZNL50oldTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- ZNL50normalTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50normalTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ZNL50normalTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ZNL50normalTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- ZNL50modernTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50modernTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ZNL50modernTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.ZNL50modernTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- ZNL50seat
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50seat");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ZNL50seat");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.ZNL50seat");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- ZNL50boxLid
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ZNL50boxLid");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ZNL50boxLid");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ZNL50boxLid");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);