-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["fears_corpses_2"] = {{ name = "other", tiles = {"fears_corpses_10", "fears_corpses_10"} }}
overlayMap["fears_corpses_3"] = {{ name = "other", tiles = {"fears_corpses_11", "fears_corpses_11"} }}
overlayMap["fears_corpses_4"] = {{ name = "other", tiles = {"fears_corpses_12", "fears_corpses_12"} }}
overlayMap["fears_corpses_5"] = {{ name = "other", tiles = {"fears_corpses_13", "fears_corpses_13"} }}
overlayMap["fears_rp_tiles_14"] = {{ name = "other", tiles = {"fears_rp_tiles_30", "fears_rp_tiles_30"} }}
overlayMap["fears_rp_tiles_15"] = {{ name = "other", tiles = {"fears_rp_tiles_31", "fears_rp_tiles_31"} }}
overlayMap["fears_rp_tiles_22"] = {{ name = "other", tiles = {"fears_rp_tiles_28", "fears_rp_tiles_28"} }}
overlayMap["fears_rp_tiles_23"] = {{ name = "other", tiles = {"fears_rp_tiles_29", "fears_rp_tiles_29"} }}
overlayMap["fears_storage_tiles_0"] = {{ name = "other", tiles = {"fears_overlays_16", "fears_overlays_8"} }}
overlayMap["fears_storage_tiles_1"] = {{ name = "other", tiles = {"fears_overlays_17", "fears_overlays_9"} }}
overlayMap["fears_storage_tiles_2"] = {{ name = "other", tiles = {"fears_overlays_18", "fears_overlays_10"} }}
overlayMap["fears_storage_tiles_3"] = {{ name = "other", tiles = {"fears_overlays_19", "fears_overlays_11"} }}
overlayMap["fears_storage_tiles_9"] = {{ name = "other", tiles = {"fears_overlays_1", "fears_overlays_0"} }}
overlayMap["fears_storage_tiles_10"] = {{ name = "other", tiles = {"fears_overlays_3", "fears_overlays_2"} }}
overlayMap["fears_workbenches_22"] = {{ name = "other", tiles = {"fears_overlays_20", "fears_overlays_22"} }}
overlayMap["fears_workbenches_23"] = {{ name = "other", tiles = {"fears_overlays_21", "fears_overlays_23"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
