require 'Items/SuburbsDistributions'
require 'Items/Distributions'

--- Magazine
--table.insert(SuburbsDistributions["all"]["postbox"].items, "HMWeapons.BaseballMagazine");
--table.insert(SuburbsDistributions["all"]["postbox"].items, 0.3);
--table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, "HMWeapons.BaseballMagazine");
--table.insert(ProceduralDistributions["list"]["MagazineRackMixed"].items, 1);
--table.insert(ProceduralDistributions["list"]["StoreShelfMechanics"].items, "HMWeapons.BaseballMagazine");
---table.insert(ProceduralDistributions["list"]["StoreShelfMechanics"].items, 1);
--table.insert(ProceduralDistributions["list"]["BookstoreBooks"].items, "HMWeapons.BaseballMagazine");
--table.insert(ProceduralDistributions["list"]["BookstoreBooks"].items, 2);
--table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, "HMWeapons.BaseballMagazine");
--table.insert(ProceduralDistributions["list"]["BedroomSideTable"].items, 0.2);
--table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, "HMWeapons.BaseballMagazine");
--table.insert(ProceduralDistributions["list"]["ClassroomShelves"].items, 2);

--- Chisel

--[[table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 8);
table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, 8);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.6);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 8);
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 8);
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, 8);
table.insert(ProceduralDistributions["list"]["LoggingFactoryTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["LoggingFactoryTools"].items, 10);
table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, 8);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 8);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 6);]]

table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CabinetFactoryTools"].items, 5);
table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, 6);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 5);
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 5);
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, 5);
table.insert(ProceduralDistributions["list"]["LoggingFactoryTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["LoggingFactoryTools"].items, 6);
table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, 5);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 5);
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, "HMWeapons.Chisel");
table.insert(ProceduralDistributions["list"]["ClosetShelfGeneric"].items, 0.3);

table.insert(ProceduralDistributions["list"]["CrateMetalwork"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["CrateMetalwork"].items, 10);
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["CrateRandomJunk"].items, 0.6);
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["GarageMetalwork"].items, 10);
table.insert(ProceduralDistributions["list"]["ToolStoreMetalwork"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["ToolStoreMetalwork"].items, 8);
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 3);
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "BarbedWire");
table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 10);