require "Items/ProceduralDistributions"
-- 89BroncoBumperFront
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.89BroncoBumperFront");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.89BroncoBumperFront");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.89BroncoBumperFront");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- 89BroncoBumperRear
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.89BroncoBumperRear");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89BroncoBumperRear");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89BroncoBumperRear");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- 89BroncoWindshield2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89BroncoWindshield2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89BroncoWindshield2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.89BroncoWindshield2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);