require "Vehicles/VehicleDistributions"

CommonVehicleDistributions = CommonVehicleDistributions or {};

CommonVehicleDistributions.Stove = {
    rolls = 3,
    items = {
        "Pot", 10,
        "Pan", 10,
        "GridlePan", 5,
        "RoastingPan", 5,
        "BakingPan", 5,
        "Kettle", 10,
        "Frog", 2,
    }
}

CommonVehicleDistributions.Microwave = {
    rolls = 3,
    items = {
        "Bowl", 10,
        "WaterBowl", 5,
        "Mugl", 10,
        "WaterMug", 5,
    }
}


CommonVehicleDistributions.Fridge = {
    rolls = 3,
    items = {
        "Milk", 8,
        "Milk", 4,
        "BeefJerky", 3,
        "Bread", 4,
        "Carrots", 4,
        "Steak", 3,
        "MeatPatty", 3,
        "Chicken", 3,
        "Ham", 3,
        "Salmon", 3,
        "Cheese", 4,
        "Watermelon", 4,
        "Broccoli", 4,
        "Pie", 3,
        "PopBottle", 3,
        "PopBottle", 3,
        "Butter", 3,
        "EggCarton", 4,
        "EggCarton", 2,
        "Apple", 4,
        "Orange", 4,
        "Banana", 4,
        "farming.RedRadish", 4,
        "farming.Strewberrie", 4,
        "Cherry", 4,
        "farming.Tomato", 4,
        "farming.Cabbage", 4,
        "Lettuce", 3,
        "Pickles", 3,
        "BellPepper", 3,
        "Peach", 3,
        "CakeSlice", 3,
        "Mustard", 2,
        "Ketchup", 2,
        "Processedcheese", 5,
        "Corndog", 2,
        "PorkChop", 3,
        "MuttonChop", 3,
        "Onion", 3,
        "Lemon", 3,
        "WaterBottleFull", 3,
        "WaterBottleFull", 3,
        "WaterBottleFull", 3,
        "Wine", 2,
        "Corn", 4,
        "Eggplant", 4,
        "Leek", 4,
        "Grapes", 4,
        "farming.Bacon", 4,
        "farming.MayonnaiseFull", 2,
        "farming.RemouladeFull", 0.5,
        "Worm", 0.3,
        "Avocado", 3,
        "Pineapple", 3,
        "Zucchini", 3,
        "Tofu", 2,
        "Yoghurt", 3,
        "JuiceBox", 1,
        "BeerCan", 1,
        "BeerCan", 1,
        "BeerCan", 1,
        "BeerBottle", 1,
    }
}

CommonVehicleDistributions.Freezer = {
    rolls = 3,
    items = {
        "Icecream", 2,
        "Icecream", 2,
        "Icecream", 2,
        "Pizza", 2,
        "Burger", 2,
        "Peas", 2,
        "Pie", 2,
        "Steak", 2,
        "Chicken", 2,
        "Salmon", 2,
        "Coldpack", 2,
        "Coldpack", 2,
        "PorkChop", 2,
        "MuttonChop", 2,
        "IcePick", 0.4,
    }
}

CommonVehicleDistributions.Counter = {
    rolls = 3,
    items = {
        "Battery", 2,
        "Lighter", 2,
        "Torch", 2,
        "HandTorch", 3,
        "HuntingKnife", 0.5,
        "DeadRat", 0.5,
        "DeadMouse", 0.5,
        "farming.CarrotBagSeed", 1,
        "farming.BroccoliBagSeed", 1,
        "farming.RedRadishBagSeed", 1,
        "farming.StrewberrieBagSeed", 1,
        "farming.TomatoBagSeed", 1,
        "farming.PotatoBagSeed", 1,
        "farming.CabbageBagSeed", 1,
        "Pistol", 0.3,
        "Revolver_Short", 0.3,
        "DoubleBarrelShotgun", 0.5,
        "ShotgunShells", 0.6,
        "BaseballBat", 0.3,
        "Bullets9mm", 0.6,
        "Bullets38", 0.6,
        "Radio.RadioBlack",2,
        "Radio.RadioRed",1,
        "Radio.WalkieTalkie1",0.05,
        "Radio.WalkieTalkie2",0.03,
        "Radio.WalkieTalkie3",0.001,
    },
    
    junk = {
        rolls = 1,
        items = {
            "Pen", 4,
            "BluePen", 2,
            "RedPen", 2,
            "Pencil", 4,
            "RubberBand", 2,
            "Tissue", 4,
            "Candle", 4,
            "Matches", 4,
            "Mugl", 7,
            "EmptyJar", 1,
            "JarLid", 1,
            "Vinegar", 1,
        },
    },
}


CommonVehicleDistributions.Wardrobe = {
    rolls = 3,
    items = {
        "PistolCase1", 0.3,
        "PistolCase2", 0.2,
        "Bag_Satchel", 0.3,
        "DumbBell", 0.2,
        "BarBell", 0.2,
        "Hat_BucketHat", 0.6,
        "Shoes_FlipFlop", 0.6,
        "Bag_FannyPackFront", 0.8,
        "Shoes_Random", 1.5,
        "Shoes_TrainerTINT", 1.5,
        "Bag_NormalHikingBag", 0.8,
        "Bag_BigHikingBag", 0.5,
        "Bag_DuffelBagTINT", 0.8,
        "LongJohns_Bottoms", 1,
        "LongJohns", 1,
        "Shorts_LongDenim", 1,
        "Trousers", 2,
        "TrousersMesh_DenimLight", 2,
        "Trousers_DefaultTEXTURE", 2,
        "Trousers_DefaultTEXTURE_HUE", 2,
        "Trousers_DefaultTEXTURE_TINT", 2,
        "Trousers_Denim", 2,
        "Trousers_Padded", 0.3,
        "Trousers_Suit", 0.3,
        "Trousers_SuitTEXTURE", 0.3,
        "Trousers_WhiteTINT", 2,
        "Shirt_FormalWhite", 1,
        "Shirt_FormalWhiteTINT", 1,
        "Shirt_FormalWhite_ShortSleeve", 1,
        "Shirt_FormalWhite_ShortSleeveTINT", 1,
        "Tshirt_DefaultTEXTURE_TINT",2.5,
        "Tshirt_PoloTINT",0.7,
        "Tshirt_WhiteLongSleeveTINT",1.5,
        "Tshirt_WhiteTINT", 2,
        "Vest_DefaultTEXTURE_TINT", 1,
        "JacketLong_Random", 0.3,
        "Jacket_Black", 0.3,
        "Jacket_Padded", 0.3,
        "Jacket_WhiteTINT", 0.5,
        "Jumper_DiamondPatternTINT", 0.3,
        "Jumper_PoloNeck", 0.5,
        "Jumper_RandomTEXTURE", 1,
        "Jumper_RoundNeck", 0.5,
        "Jumper_TankTopTINT", 0.3,
        "HoodieDOWN_WhiteTINT", 0.5,
        "Jumper_VNeck", 0.5,
        "Hat_EarMuffs", 0.1,
        "Hat_Fedora", 0.2,
        "Hat_WoolyHat", 0.1,
        "Gloves_WhiteTINT", 0.1,
        "Gloves_FingerlessGloves", 0.6,
        "Gloves_LeatherGloves", 0.05,
        "Gloves_LeatherGlovesBlack", 0.05,
        "SwimTrunks_Blue", 0.1,
        "SwimTrunks_Green", 0.1,
        "SwimTrunks_Red", 0.1,
        "SwimTrunks_Yellow", 0.1,
        "BaseballBat", 0.08,
        "Scarf_White", 0.02,
        "Scarf_StripeBlackWhite", 0.02,
        "Scarf_StripeBlueWhite", 0.02,
        "Scarf_StripeRedWhite", 0.02,
        "Saxophone", 0.02,
        "Trumpet", 0.02,
        "GuitarAcoustic", 0.03,
        "GuitarElectricBlack", 0.03,
        "GuitarElectricBlue", 0.03,
        "GuitarElectricRed", 0.03,
        "GuitarElectricBassBlue", 0.03,
        "GuitarElectricBassBlack", 0.03,
        "GuitarElectricBassRed", 0.03,
        "Flightcase", 0.05,
        "Guitarcase", 0.05,
        "Keytar", 0.02,
        "DoubleBarrelShotgun", 0.5,
        "Suitcase", 0.3,
        "Briefcase", 0.3,
    },
    junk = {
        rolls = 2,
        items = {
            "ClosedUmbrellaRed", 0.3,
            "ClosedUmbrellaBlue", 0.3,
            "ClosedUmbrellaBlack", 0.3,
            "ClosedUmbrellaWhite", 0.3,
            "AlarmClock2", 2,
            "Disc", 0.5,
            "CDplayer", 0.5,
            "Earbuds", 0.5,
            "Headphones", 0.5,
            "VideoGame", 0.5,
            "Pillow", 9,
            "Belt2", 5,
            "Socks_Ankle", 4,
            "Socks_Ankle", 4,
            "Socks_Long", 2,
        },
    },
}

CommonVehicleDistributions.Shelves = {
    rolls = 3,
    items = {
        "Magazine", 10,
        "Newspaper", 10,
        "Book", 10,
        "SheetPaper2", 10,
        "Notebook", 10,
        "BookCarpentry1", 2,
        "BookCarpentry2", 1,
        "BookCarpentry3", 0.7,
        "BookCarpentry4", 0.5,
        "BookCarpentry5", 0.3,
        "BookCooking1", 2,
        "BookCooking2", 1,
        "BookCooking3", 0.5,
        "BookCooking4", 0.3,
        "BookForaging1", 2,
        "BookForaging2", 1,
        "BookForaging3", 0.7,
        "BookForaging4", 0.5,
        "BookForaging5", 0.3,
        "BookFarming1", 2,
        "BookFarming2", 1,
        "BookFarming3", 0.7,
        "BookFarming4", 0.5,
        "BookFarming5", 0.3,
        "BookFishing1", 2,
        "BookFishing2", 1,
        "BookFishing3", 0.7,
        "BookFishing4", 0.5,
        "BookFishing5", 0.3,
        "BookTrapping1", 2,
        "BookTrapping2", 1,
        "BookTrapping3", 0.7,
        "BookTrapping4", 0.5,
        "BookTrapping5", 0.3,
        "BookFirstAid1", 2,
        "BookFirstAid2", 1,
        "BookFirstAid3", 0.7,
        "BookFirstAid4", 0.5,
        "BookFirstAid5", 0.3,
        "BookMetalWelding1", 2,
        "BookMetalWelding2", 1,
        "BookMetalWelding3", 0.7,
        "BookMetalWelding4", 0.5,
        "BookMetalWelding5", 0.3,
        "BookElectrician1", 2,
        "BookElectrician2", 1,
        "BookElectrician3", 0.7,
        "BookElectrician4", 0.5,
        "BookElectrician5", 0.3,
        "BookMechanic1", 2,
        "BookMechanic2", 1,
        "BookMechanic3", 0.7,
        "BookMechanic4", 0.5,
        "BookMechanic5", 0.3,
        "FishingMag1", 1,
        "FishingMag2", 1,
        "HuntingMag1", 1,
        "HuntingMag2", 1,
        "HuntingMag3", 1,
        "HerbalistMag", 1,
        "CookingMag1", 1,
        "CookingMag2", 1,
        "ElectronicsMag1", 1,
        "ElectronicsMag2", 1,
        "ElectronicsMag3", 1,
        "ElectronicsMag4", 1,
        "ElectronicsMag5", 1,
        "MechanicMag1", 1,
        "MechanicMag2", 1,
        "MechanicMag3", 1,
        "EngineerMagazine1", 1,
        "EngineerMagazine2", 1,
        "MetalworkMag1", 1,
        "MetalworkMag2", 1,
        "MetalworkMag3", 1,
        "MetalworkMag4", 1,
        "Journal", 2,
        "Radio.RadioBlack",2,
        "Radio.RadioRed",1,
    }
}

CommonVehicleDistributions.Sidetable = {
    rolls = 3,
    items = {
        "Battery", 2,
        "Lighter", 2,
        "Torch", 1,
        "HandTorch", 1.5,
        "Journal", 2,
        "Magazine", 4,
        "Newspaper", 4,
        "Book", 4,
        "ComicBook", 2,
        "Cigarettes", 4,
        "BookCarpentry1", 1,
        --                "BookBlacksmith1", 1,
        "BookFirstAid1", 1,
        "BookMetalWelding1", 1,
        "BookMetalWelding1", 1,
        "BookElectrician1", 1,
        "BookMechanic1" , 1,
        "BookFarming1", 1,
        "BookForaging1", 1,
        "BookCooking1", 1,
        "BookFishing1", 1,
        "BookTrapping1", 1,
        "BookCarpentry2", 0.5,
        "BookFarming2", 0.5,
        "BookForaging2", 0.5,
        "BookCooking2", 0.5,
        "BookFishing2", 0.5,
        "BookTrapping2", 0.5,
        --                "BookBlacksmith2", 0.5,
        "BookFirstAid2", 0.5,
        "BookMetalWelding2", 0.5,
        "BookElectrician2", 0.5,
        "BookMechanic2", 0.5,
        "Key1", 1,
        "Key2", 1,
        "Key3", 1,
        "Key4", 1,
        "Key5", 1,
        "HomeAlarm", 1,
        "Radio.RadioBlack",2,
        "Radio.RadioRed",1,
        "Radio.WalkieTalkie1",0.05,
        "Radio.WalkieTalkie2",0.03,
        "Radio.WalkieTalkie3",0.001,
        "Remote", 8,
        "MuldraughMap", 0.05,
        "WestpointMap", 0.05,
        "MarchRidgeMap",0.01,
        "RosewoodMap",0.01,
        "RiversideMap",0.01,
        "FishingMag1", 0.7,
        "FishingMag2", 0.7,
        "HuntingMag1", 0.7,
        "HuntingMag2", 0.7,
        "HuntingMag3", 0.7,
        "HerbalistMag", 0.7,
        "CookingMag1", 0.7,
        "CookingMag2", 0.7,
        "ElectronicsMag1", 0.7,
        "ElectronicsMag2", 0.7,
        "ElectronicsMag3", 0.7,
        "ElectronicsMag4", 0.7,
        "ElectronicsMag5", 0.7,
        "MechanicMag1", 0.7,
        "MechanicMag2", 0.7,
        "MechanicMag3", 0.7,
        "EngineerMagazine1", 0.7,
        "EngineerMagazine2", 0.7,
        "MetalworkMag1", 0.7,
        "MetalworkMag2", 0.7,
        "MetalworkMag3", 0.7,
        "MetalworkMag4", 0.7,
    },
    junk = {
        rolls = 1,
        items = {
            "Pen", 4,
            "BluePen", 2,
            "RedPen", 2,
            "Paperclip", 1,
            "Pencil", 4,
            "RubberBand", 2,
            "Eraser", 4,
            "Tissue", 9,
            "Candle", 4,
            "Matches", 3,
            "SheetPaper2", 4,
            "Notebook", 4,
        },
    },
}

CommonVehicleDistributions.Medicine = {
    rolls = 3,
    items = {
        "Bandaid", 7,
        "Pills", 7,
        "PillsBeta", 7,
        "PillsAntiDep", 7,
        "PillsSleepingTablets", 7,
        "PillsVitamins", 7,
        "Tweezers", 5,
        "Antibiotics", 5,
    }
}

CommonVehicleDistributions.Null = {
    rolls = 1,
    items = {
    }
}

CommonVehicleDistributions.Holster = {
    rolls = 4,
    items = {
        "308Box", 10,
        "AmmoStrap_Bullets", 4,
        "AmmoStrap_Shells", 4,
        "AssaultRifle2", 1,
        "Bullets9mmBox", 20,
        "Bullets9mmBox", 10,
        "HandTorch", 4,
        "HolsterDouble", 1,
        "HolsterSimple", 4,
        "HuntingRifle", 8,
        "M14Clip", 4,
        "Nightstick", 2,
        "Pistol", 10,
        "Radio.WalkieTalkie4", 10,
        "Shotgun", 10,
        "ShotgunShellsBox", 10,
        "x2Scope", 4,
        "x4Scope", 2,
        "x8Scope", 1,
    },
    junk = {
        rolls = 1,
        items = {
            "FirstAidKit", 20,
        }
    }
}


VehicleDistributions.CommonTemplatesDist = {
    stove = CommonVehicleDistributions.Stove,
    portablemicrowave = CommonVehicleDistributions.Microwave,
    fridge = CommonVehicleDistributions.Fridge,
    freezer = CommonVehicleDistributions.Freezer,
    counter = CommonVehicleDistributions.Counter,
    wardrobe = CommonVehicleDistributions.Wardrobe,
    shelves = CommonVehicleDistributions.Shelves,
    sidetable = CommonVehicleDistributions.Sidetable,
    medicine = CommonVehicleDistributions.Medicine,
    seatboxwooden = CommonVehicleDistributions.FishermanTruckBed,
    GloveBox = CommonVehicleDistributions.GloveBox,
    
    
    CupboardFrontLeft = CommonVehicleDistributions.Null,
    CupboardFrontRight = CommonVehicleDistributions.Null,
    CupboardMiddleLeft = CommonVehicleDistributions.Null,
    CupboardMiddleRight = CommonVehicleDistributions.Null,
    CupboardRearLeft = CommonVehicleDistributions.Null,
    CupboardRearRight = CommonVehicleDistributions.Null,
    
    CounterFrontLeft = CommonVehicleDistributions.Null,
    CounterFrontRight = CommonVehicleDistributions.Null,
    CounterMiddleLeft = CommonVehicleDistributions.Null,
    CounterMiddleRight = CommonVehicleDistributions.Null,
    CounterRearLeft = CommonVehicleDistributions.Null,
    CounterRearRight = CommonVehicleDistributions.Null,
    
    DrawerFrontLeft = CommonVehicleDistributions.Null,
    DrawerFrontRight = CommonVehicleDistributions.Null,
    DrawerMiddleLeft = CommonVehicleDistributions.Null,
    DrawerMiddleRight = CommonVehicleDistributions.Null,
    DrawerRearLeft = CommonVehicleDistributions.Null,
    DrawerRearRight = CommonVehicleDistributions.Null,
    
    MedicineFrontLeft = CommonVehicleDistributions.Null,
    MedicineFrontRight = CommonVehicleDistributions.Null,
    MedicineMiddleLeft = CommonVehicleDistributions.Null,
    MedicineMiddleRight = CommonVehicleDistributions.Null,
    MedicineRearLeft = CommonVehicleDistributions.Null,
    MedicineRearRight = CommonVehicleDistributions.Null,

    ShelveFrontLeft = CommonVehicleDistributions.Null,
    ShelveFrontRight = CommonVehicleDistributions.Null,
    ShelveMiddleLeft = CommonVehicleDistributions.Null,
    ShelveMiddleRight = CommonVehicleDistributions.Null,
    ShelveRearLeft = CommonVehicleDistributions.Null,
    ShelveRearRight = CommonVehicleDistributions.Null,

    FridgeFrontLeft = CommonVehicleDistributions.Null,
    FridgeFrontRight = CommonVehicleDistributions.Null,
    FridgeMiddleLeft = CommonVehicleDistributions.Null,
    FridgeMiddleRight = CommonVehicleDistributions.Null,
    FridgeRearLeft = CommonVehicleDistributions.Null,
    FridgeRearRight = CommonVehicleDistributions.Null,
    
    FreezerFrontLeft = CommonVehicleDistributions.Null,
    FreezerFrontRight = CommonVehicleDistributions.Null,
    FreezerMiddleLeft = CommonVehicleDistributions.Null,
    FreezerMiddleRight = CommonVehicleDistributions.Null,
    FreezerRearLeft = CommonVehicleDistributions.Null,
    FreezerRearRight = CommonVehicleDistributions.Null,

    OvenFrontLeft = CommonVehicleDistributions.Null,
    OvenFrontRight = CommonVehicleDistributions.Null,
    OvenMiddleLeft = CommonVehicleDistributions.Null,
    OvenMiddleRight = CommonVehicleDistributions.Null,
    OvenRearLeft = CommonVehicleDistributions.Null,
    OvenRearRight = CommonVehicleDistributions.Null,

    MicrowaveFrontLeft = CommonVehicleDistributions.Null,
    MicrowaveFrontRight = CommonVehicleDistributions.Null,
    MicrowaveMiddleLeft = CommonVehicleDistributions.Null,
    MicrowaveMiddleRight = CommonVehicleDistributions.Null,
    MicrowaveRearLeft = CommonVehicleDistributions.Null,
    MicrowaveRearRight = CommonVehicleDistributions.Null,
    
    ATABagOnProtectionWindowFrontLeft = VehicleDistributions.SurvivalistTruckBed,
    ATABagOnProtectionWindowFrontRight = VehicleDistributions.SurvivalistTruckBed,
    ATABagMotoLeft = VehicleDistributions.SurvivalistTruckBed,
    ATABagMotoRight = VehicleDistributions.SurvivalistTruckBed,
    ATABagMotoHolsterLeft = CommonVehicleDistributions.Holster,
    ATABagMotoHolsterRight = CommonVehicleDistributions.Holster,
    
    ATAInteractiveTrunkRoofRack = VehicleDistributions.SurvivalistTruckBed,
    ATAInteractiveTrunkWindowRearRack = VehicleDistributions.SurvivalistTruckBed,
    ATAInteractiveTrunkWheelRack = VehicleDistributions.SurvivalistTruckBed,
    ATAInteractiveTrunkFront = VehicleDistributions.SurvivalistTruckBed,
    ATAInteractiveTrunkRear = VehicleDistributions.SurvivalistTruckBed,
}
