-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Skizot_tiles_16"] = {{ name = "other", tiles = {"Skizot_tiles_40", "Skizot_tiles_40"} }}
overlayMap["Skizot_tiles_17"] = {{ name = "other", tiles = {"Skizot_tiles_41", "Skizot_tiles_41"} }}
overlayMap["Skizot_tiles_18"] = {{ name = "other", tiles = {"Skizot_tiles_42", "Skizot_tiles_42"} }}
overlayMap["Skizot_tiles_19"] = {{ name = "other", tiles = {"Skizot_tiles_43", "Skizot_tiles_43"} }}
overlayMap["Skizot_tiles_20"] = {{ name = "other", tiles = {"Skizot_tiles_44", "Skizot_tiles_44"} }}
overlayMap["Skizot_tiles_21"] = {{ name = "other", tiles = {"Skizot_tiles_45", "Skizot_tiles_45"} }}
overlayMap["Skizot_tiles_22"] = {{ name = "other", tiles = {"Skizot_tiles_46", "Skizot_tiles_46"} }}
overlayMap["Skizot_tiles_23"] = {{ name = "other", tiles = {"Skizot_tiles_47", "Skizot_tiles_47"} }}
overlayMap["Skizot_tiles_54"] = {{ name = "other", tiles = {"Skizot_tiles_62", "Skizot_tiles_62"} }}
overlayMap["Skizot_tiles_55"] = {{ name = "other", tiles = {"Skizot_tiles_63", "Skizot_tiles_63"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
