require "Items/ProceduralDistributions"
-- CUDAtire3
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.CUDAtire3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.CUDAtire3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.CUDAtire3");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.CUDAtire3");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.CUDAtire3");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.5);
-- CUDAFrontBumperA
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.CUDAFrontBumper0");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.CUDAFrontBumper0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.CUDAFrontBumper1");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.4);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.CUDAFrontBumper2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.CUDAFrontBumperA");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.3);
-- CUDASpoiler0
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.CUDASpoiler0");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.CUDASpoiler0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.CUDASpoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.CUDASpoiler0");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.CUDASpoiler0");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- CUDASpoiler1
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.CUDASpoiler1");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.CUDASpoiler1");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.CUDASpoiler1");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.CUDASpoiler1");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.CUDASpoiler1");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);