-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Chinatown_EX_1_80"] = {{ name = "other", tiles = {"Chinatown_EX_1_88", "Chinatown_EX_1_88"} }}
overlayMap["Chinatown_EX_3_26"] = {{ name = "other", tiles = {"Chinatown_EX_3_27", "Chinatown_EX_3_27"} }}
overlayMap["Chinatown_EX_3_28"] = {{ name = "other", tiles = {"Chinatown_EX_3_30", "Chinatown_EX_3_30"} }}
overlayMap["Chinatown_EX_3_29"] = {{ name = "other", tiles = {"Chinatown_EX_3_31", "Chinatown_EX_3_31"} }}
overlayMap["Chinatown_EX_generic_1_0"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_8", "Chinatown_EX_generic_1_9"} }}
overlayMap["Chinatown_EX_generic_1_1"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_10", "Chinatown_EX_generic_1_11"} }}
overlayMap["Chinatown_EX_generic_1_2"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_8", "Chinatown_EX_generic_1_9"} }}
overlayMap["Chinatown_EX_generic_1_3"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_10", "Chinatown_EX_generic_1_11"} }}
overlayMap["Chinatown_EX_generic_1_4"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_12", "Chinatown_EX_generic_1_14"} }}
overlayMap["Chinatown_EX_generic_1_5"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_13", "Chinatown_EX_generic_1_15"} }}
overlayMap["Chinatown_EX_generic_1_16"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_24", "Chinatown_EX_generic_1_28"} }}
overlayMap["Chinatown_EX_generic_1_17"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_25", "Chinatown_EX_generic_1_29"} }}
overlayMap["Chinatown_EX_generic_1_18"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_26", "Chinatown_EX_generic_1_30"} }}
overlayMap["Chinatown_EX_generic_1_19"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_27", "Chinatown_EX_generic_1_31"} }}
overlayMap["Chinatown_EX_generic_1_32"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_36", "Chinatown_EX_generic_1_36"} }}
overlayMap["Chinatown_EX_generic_1_33"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_37", "Chinatown_EX_generic_1_37"} }}
overlayMap["Chinatown_EX_generic_1_80"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_88", "Chinatown_EX_generic_1_92"} }}
overlayMap["Chinatown_EX_generic_1_81"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_89", "Chinatown_EX_generic_1_93"} }}
overlayMap["Chinatown_EX_generic_1_82"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_90", "Chinatown_EX_generic_1_94"} }}
overlayMap["Chinatown_EX_generic_1_83"] = {{ name = "other", tiles = {"Chinatown_EX_generic_1_91", "Chinatown_EX_generic_1_95"} }}
overlayMap["Chinatown_EX_home_2_80"] = {{ name = "other", tiles = {"Chinatown_EX_home_2_82", "Chinatown_EX_home_2_82"} }}
overlayMap["Chinatown_EX_home_2_81"] = {{ name = "other", tiles = {"Chinatown_EX_home_2_83", "Chinatown_EX_home_2_83"} }}
overlayMap["Chinatown_EX_military_1_0"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_4", "Chinatown_EX_military_1_4"} }}
overlayMap["Chinatown_EX_military_1_1"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_5", "Chinatown_EX_military_1_5"} }}
overlayMap["Chinatown_EX_military_1_2"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_6", "Chinatown_EX_military_1_6"} }}
overlayMap["Chinatown_EX_military_1_3"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_7", "Chinatown_EX_military_1_7"} }}
overlayMap["Chinatown_EX_military_1_8"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_12", "Chinatown_EX_military_1_12"} }}
overlayMap["Chinatown_EX_military_1_9"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_13", "Chinatown_EX_military_1_13"} }}
overlayMap["Chinatown_EX_military_1_10"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_14", "Chinatown_EX_military_1_14"} }}
overlayMap["Chinatown_EX_military_1_11"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_15", "Chinatown_EX_military_1_15"} }}
overlayMap["Chinatown_EX_military_1_16"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_20", "Chinatown_EX_military_1_20"} }}
overlayMap["Chinatown_EX_military_1_17"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_21", "Chinatown_EX_military_1_21"} }}
overlayMap["Chinatown_EX_military_1_18"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_22", "Chinatown_EX_military_1_22"} }}
overlayMap["Chinatown_EX_military_1_19"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_23", "Chinatown_EX_military_1_23"} }}
overlayMap["Chinatown_EX_military_1_24"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_28", "Chinatown_EX_military_1_36"} }}
overlayMap["Chinatown_EX_military_1_25"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_29", "Chinatown_EX_military_1_37"} }}
overlayMap["Chinatown_EX_military_1_26"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_30", "Chinatown_EX_military_1_38"} }}
overlayMap["Chinatown_EX_military_1_27"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_31", "Chinatown_EX_military_1_39"} }}
overlayMap["Chinatown_EX_military_1_40"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_44", "Chinatown_EX_military_1_52"} }}
overlayMap["Chinatown_EX_military_1_41"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_45", "Chinatown_EX_military_1_53"} }}
overlayMap["Chinatown_EX_military_1_42"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_46", "Chinatown_EX_military_1_54"} }}
overlayMap["Chinatown_EX_military_1_43"] = {{ name = "other", tiles = {"Chinatown_EX_military_1_47", "Chinatown_EX_military_1_55"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
