-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Vault_8_35"] = {{ name = "other", tiles = {"Vault_8_36", "Vault_8_36"} }}
overlayMap["Vaulttec_1_12"] = {{ name = "other", tiles = {"Vaulttec_1_20", "Vaulttec_1_20"} }}
overlayMap["Vaulttec_1_13"] = {{ name = "other", tiles = {"Vaulttec_1_21", "Vaulttec_1_21"} }}
overlayMap["Vaulttec_1_14"] = {{ name = "other", tiles = {"Vaulttec_1_22", "Vaulttec_1_22"} }}
overlayMap["Vaulttec_1_15"] = {{ name = "other", tiles = {"Vaulttec_1_23", "Vaulttec_1_23"} }}
overlayMap["Vaulttec_1_24"] = {{ name = "other", tiles = {"Vaulttec_1_32", "Vaulttec_1_32"} }}
overlayMap["Vaulttec_1_25"] = {{ name = "other", tiles = {"Vaulttec_1_33", "Vaulttec_1_33"} }}
overlayMap["Vaulttec_1_26"] = {{ name = "other", tiles = {"Vaulttec_1_34", "Vaulttec_1_34"} }}
overlayMap["Vaulttec_1_27"] = {{ name = "other", tiles = {"Vaulttec_1_35", "Vaulttec_1_35"} }}
overlayMap["Vaulttec_1_28"] = {{ name = "other", tiles = {"Vaulttec_1_36", "Vaulttec_1_36"} }}
overlayMap["Vaulttec_1_29"] = {{ name = "other", tiles = {"Vaulttec_1_37", "Vaulttec_1_37"} }}
overlayMap["Vaulttec_1_30"] = {{ name = "other", tiles = {"Vaulttec_1_38", "Vaulttec_1_38"} }}
overlayMap["Vaulttec_1_31"] = {{ name = "other", tiles = {"Vaulttec_1_39", "Vaulttec_1_39"} }}
overlayMap["Vaulttec_2_0"] = {{ name = "other", tiles = {"Vaulttec_2_8", "Vaulttec_2_8"} }}
overlayMap["Vaulttec_2_1"] = {{ name = "other", tiles = {"Vaulttec_2_9", "Vaulttec_2_9"} }}
overlayMap["Vaulttec_2_2"] = {{ name = "other", tiles = {"Vaulttec_2_10", "Vaulttec_2_10"} }}
overlayMap["Vaulttec_2_3"] = {{ name = "other", tiles = {"Vaulttec_2_11", "Vaulttec_2_11"} }}
overlayMap["Vaulttec_2_32"] = {{ name = "other", tiles = {"Vaulttec_2_40", "Vaulttec_2_40"} }}
overlayMap["Vaulttec_2_33"] = {{ name = "other", tiles = {"Vaulttec_2_41", "Vaulttec_2_41"} }}
overlayMap["Vaulttec_2_34"] = {{ name = "other", tiles = {"Vaulttec_2_50", "Vaulttec_2_50"} }}
overlayMap["Vaulttec_2_35"] = {{ name = "other", tiles = {"Vaulttec_2_51", "Vaulttec_2_51"} }}
overlayMap["Vaulttec_2_36"] = {{ name = "other", tiles = {"Vaulttec_2_44", "Vaulttec_2_52"} }}
overlayMap["Vaulttec_2_37"] = {{ name = "other", tiles = {"Vaulttec_2_45", "Vaulttec_2_53"} }}
overlayMap["Vaulttec_2_38"] = {{ name = "other", tiles = {"Vaulttec_2_46", "Vaulttec_2_54"} }}
overlayMap["Vaulttec_2_39"] = {{ name = "other", tiles = {"Vaulttec_2_47", "Vaulttec_2_55"} }}
overlayMap["Vaulttec_2_42"] = {{ name = "other", tiles = {"Vaulttec_2_48", "Vaulttec_2_48"} }}
overlayMap["Vaulttec_2_43"] = {{ name = "other", tiles = {"Vaulttec_2_49", "Vaulttec_2_49"} }}
overlayMap["Vaulttec_3_28"] = {{ name = "other", tiles = {"Vaulttec_3_30", "Vaulttec_3_30"} }}
overlayMap["Vaulttec_3_29"] = {{ name = "other", tiles = {"Vaulttec_3_31", "Vaulttec_3_31"} }}
overlayMap["Vaulttec_3_34"] = {{ name = "other", tiles = {"Vaulttec_3_36", "Vaulttec_3_36"} }}
overlayMap["Vaulttec_3_35"] = {{ name = "other", tiles = {"Vaulttec_3_37", "Vaulttec_3_37"} }}
overlayMap["Vaulttec_3_48"] = {{ name = "other", tiles = {"Vaulttec_3_56", "Vaulttec_3_56"} }}
overlayMap["Vaulttec_3_49"] = {{ name = "other", tiles = {"Vaulttec_3_57", "Vaulttec_3_57"} }}
overlayMap["Vaulttec_4_46"] = {{ name = "other", tiles = {"Vaulttec_4_47", "Vaulttec_4_47"} }}
overlayMap["Vaulttec_4_48"] = {{ name = "other", tiles = {"Vaulttec_4_50", "Vaulttec_4_49"} }}
overlayMap["Vaulttec_4_51"] = {{ name = "other", tiles = {"Vaulttec_4_53", "Vaulttec_4_52"} }}
overlayMap["Vaulttec_4_54"] = {{ name = "other", tiles = {"Vaulttec_4_55", "Vaulttec_4_55"} }}
overlayMap["Vaulttec_5_2"] = {{ name = "other", tiles = {"Vaulttec_5_4", "Vaulttec_5_5"} }}
overlayMap["Vaulttec_5_3"] = {{ name = "other", tiles = {"Vaulttec_5_6", "Vaulttec_5_7"} }}
overlayMap["Vaulttec_5_13"] = {{ name = "other", tiles = {"Vaulttec_5_21", "Vaulttec_5_21"} }}
overlayMap["Vaulttec_5_14"] = {{ name = "other", tiles = {"Vaulttec_5_22", "Vaulttec_5_22"} }}
overlayMap["Vaulttec_5_15"] = {{ name = "other", tiles = {"Vaulttec_5_23", "Vaulttec_5_23"} }}
overlayMap["Vaulttec_5_16"] = {{ name = "other", tiles = {"Vaulttec_5_24", "Vaulttec_5_24"} }}
overlayMap["Vaulttec_5_17"] = {{ name = "other", tiles = {"Vaulttec_5_25", "Vaulttec_5_25"} }}
overlayMap["Vaulttec_5_29"] = {{ name = "other", tiles = {"Vaulttec_5_37", "Vaulttec_5_37"} }}
overlayMap["Vaulttec_5_30"] = {{ name = "other", tiles = {"Vaulttec_5_38", "Vaulttec_5_38"} }}
overlayMap["Vaulttec_5_31"] = {{ name = "other", tiles = {"Vaulttec_5_39", "Vaulttec_5_39"} }}
overlayMap["Vaulttec_5_42"] = {{ name = "other", tiles = {"Vaulttec_5_50", "Vaulttec_5_50"} }}
overlayMap["Vaulttec_5_43"] = {{ name = "other", tiles = {"Vaulttec_5_51", "Vaulttec_5_51"} }}
overlayMap["Vaulttec_6_40"] = {{ name = "other", tiles = {"Vaulttec_6_48", "Vaulttec_6_48"} }}
overlayMap["Vaulttec_6_41"] = {{ name = "other", tiles = {"Vaulttec_6_49", "Vaulttec_6_49"} }}
overlayMap["Vaulttec_6_42"] = {{ name = "other", tiles = {"Vaulttec_6_50", "Vaulttec_6_51"} }}
overlayMap["Vaulttec_6_43"] = {{ name = "other", tiles = {"Vaulttec_6_54", "Vaulttec_6_46"} }}
overlayMap["Vaulttec_6_44"] = {{ name = "other", tiles = {"Vaulttec_6_55", "Vaulttec_6_47"} }}
overlayMap["Vaulttec_6_45"] = {{ name = "other", tiles = {"Vaulttec_6_53", "Vaulttec_6_52"} }}
overlayMap["guizi_01_0"] = {{ name = "other", tiles = {"guizi_01_2", "guizi_01_1"} }}
overlayMap["guizi_01_5"] = {{ name = "other", tiles = {"guizi_01_7", "guizi_01_6"} }}
overlayMap["guizi_01_16"] = {{ name = "other", tiles = {"guizi_01_22", "guizi_01_21"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
