-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["Guizi_tiles_01_0"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_13", "Guizi_tiles_01_12"} }, { name = "other", tiles = {"Guizi_tiles_01_4", "Guizi_tiles_01_2"} }}
overlayMap["Guizi_tiles_01_1"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_15", "Guizi_tiles_01_14"} }, { name = "other", tiles = {"Guizi_tiles_01_5", "Guizi_tiles_01_3"} }}
overlayMap["Guizi_tiles_01_6"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_17", "Guizi_tiles_01_16"} }, { name = "other", tiles = {"Guizi_tiles_01_11", "Guizi_tiles_01_9"} }}
overlayMap["Guizi_tiles_01_7"] = {{ name = "armystorage", tiles = {"Guizi_tiles_01_19", "Guizi_tiles_01_18"} }, { name = "other", tiles = {"Guizi_tiles_01_10", "Guizi_tiles_01_8"} }}
overlayMap["Industry_3_4"] = {{ name = "other", tiles = {"Industry_3_6", "Industry_3_6"} }}
overlayMap["Industry_3_5"] = {{ name = "other", tiles = {"Industry_3_7", "Industry_3_7"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
