local trashItems = {
    ['PompsItems.Brawndo'] = 'PompsItems.BrawndoCan',
    ['PompsItems.PIRootBeer'] = 'PompsItems.PIRootBeerEmpty',
    ['PompsItems.CzechCoffee'] = 'PompsItems.CzechCoffeeEmpty',
    ['PompsItems.TaterSticks'] = 'PompsItems.TaterSticksEmpty',
	['PompsItems.JiangLi1'] = 'PompsItems.JiangLi1Empty',
	['PompsItems.JiangLi2'] = 'PompsItems.JiangLi2Empty',
	['PompsItems.JiangLi3'] = 'PompsItems.JiangLi3Empty',
	['PompsItems.JiangLi4'] = 'PompsItems.JiangLi4Empty',
	['PompsItems.JiangLi5'] = 'PompsItems.JiangLi5Empty',
	['PompsItems.JiangLi6'] = 'PompsItems.JiangLi6Empty',
	['PompsItems.JiangLi7'] = 'PompsItems.JiangLi7Empty',
	['PompsItems.JiangLi8'] = 'PompsItems.JiangLi8Empty',
	['PompsItems.JiangLi9'] = 'PompsItems.JiangLi9Empty',
	['PompsItems.Tartsies'] = 'PompsItems.TartsiesEmpty',
	['PompsItems.SourGummies'] = 'PompsItems.SourGummiesEmpty',
	['PompsItems.GummyBearsPacket'] = 'PompsItems.GummyBearsEmpty',
	['PompsItems.PIGummyWorms'] = 'PompsItems.GummyWormsEmpty',
	['PompsItems.BittersBar'] = 'PompsItems.BittersBarEmpty',
	['PompsItems.BittersBrownie'] = 'PompsItems.BittersBrownieEmpty',
	['PompsItems.Tangsy'] = 'PompsItems.TangsyEmpty',
	['PompsItems.GummySharks'] = 'PompsItems.GummySharksEmpty',
	['PompsItems.TwistysRed'] = 'PompsItems.TwistysRedEmpty',
	['PompsItems.TwistysBlack'] = 'PompsItems.TwistysBlackEmpty',
	['PompsItems.PIJellyBeans'] = 'PompsItems.JellyBeansEmpty',
	['PompsItems.CircusPeanuts'] = 'PompsItems.CircusPeanutsEmpty',
	['PompsItems.TastyTarts'] = 'PompsItems.TastyTartsEmpty',
	['PompsItems.Dabs'] = 'PompsItems.DabsEmpty',
	['PompsItems.Sunbooms'] = 'PompsItems.SunboomsEmpty',
	['PompsItems.SunboomsTropical'] = 'PompsItems.SunboomsTropicalEmpty',
	['PompsItems.CocoGlee'] = 'PompsItems.CocoGleeEmpty',
	['PompsItems.GooberBar'] = 'PompsItems.GooberBarEmpty',
	['PompsItems.ChoccDark'] = 'PompsItems.ChoccDarkEmpty',
	['PompsItems.ChoccWhite'] = 'PompsItems.ChoccWhiteEmpty',
	['PompsItems.PIFigBar'] = 'PompsItems.PIFigBarEmpty',
	['PompsItems.RMRootBeer'] = 'PompsItems.RMRootBeerEmpty',
	['PompsItems.LugRootBeer'] = 'PompsItems.LugRootBeerEmpty',
	['PompsItems.PICheeseBallsSmall'] = 'PompsItems.PICheeseBallsSmallEmpty',
	['PompsItems.PICheeseBalls'] = 'PompsItems.PICheeseBallsEmpty',
	['PompsItems.LunchableNachosSmall'] = 'PompsItems.LunchableSmallEmpty',
	['PompsItems.PISpiffoSquish'] = 'PompsItems.PISpiffoSquishEmpty',
	['PompsItems.PICheesyPoofs'] = 'PompsItems.PICheesyPoofsEmpty',
	['PompsItems.PIFishSnackems'] = 'PompsItems.PIFishSnackemsEmpty',
	['PompsItems.PIGeeks'] = 'PompsItems.PIGeeksEmpty',
	['PompsItems.PICandyCigarettes'] = 'PompsItems.PICandyCigarettesEmpty',
	['PompsItems.PICandyCigarettes2'] = 'PompsItems.PICandyCigarettes2Empty',
	['PompsItems.PIPushPopBlue'] = 'PompsItems.PIPushPopBlueEmpty',
	['PompsItems.PIPushPopRed'] = 'PompsItems.PIPushPopRedEmpty',
	['PompsItems.PIJavaCrunch'] = 'PompsItems.PIJavaCrunchEmpty',
	['PompsItems.PITix'] = 'PompsItems.PITixEmpty',
	['PompsItems.PIElChips'] = 'PompsItems.PIElChipsEmpty',
	['PompsItems.PIWormholes'] = 'PompsItems.PIWormholesEmpty',
	['PompsItems.PIHotChachas'] = 'PompsItems.PIHotChachasEmpty',
	['PompsItems.PIIceCaps'] = 'PompsItems.PIIceCapsEmpty',
	['PompsItems.MoneyChoc'] = 'PompsItems.MoneyChocEmpty',
	['PompsItems.PISkyDullards'] = 'PompsItems.PISkyDullardsEmpty',
	['PompsItems.PIHeadHonchoChew'] = 'PompsItems.PIHeadHonchoChewEmpty',
	['PompsItems.PIDiamondCola'] = 'PompsItems.PIDiamondColaEmpty',
	['PompsItems.KFCheese'] = 'PompsItems.KFCheeseOpen',
	['PompsItems.MaplesSyrup'] = 'PompsItems.MaplesSyrupEmpty',
	['PompsItems.SbeveGin'] = 'PompsItems.SbeveEmpty',
	['PompsItems.PIChocMilk'] = 'PompsItems.ChocMilkEmpty',
	['PompsItems.VodkaAus'] = 'PompsItems.VodkaAusEmpty',
	['PompsItems.PISportsDrinkGrape'] = 'PompsItems.PISportsDrinkGrapeEmpty',
	['PompsItems.PISportsDrinkBlue'] = 'PompsItems.PISportsDrinkBlueEmpty',
	['PompsItems.PISportsDrinkFruit'] = 'PompsItems.PISportsDrinkFruitEmpty',
	['PompsItems.PISportsDrinkLemonade'] = 'PompsItems.PISportsDrinkLemonadeEmpty',
	['PompsItems.PISportsDrinkLime'] = 'PompsItems.PISportsDrinkLimeEmpty',
	['PompsItems.PISportsDrinkOrange'] = 'PompsItems.PISportsDrinkOrangeEmpty',
	['PompsItems.PIBRBarrel'] = 'PompsItems.PIFruitBarrelEmpty',
	['PompsItems.PIGreenBarrel'] = 'PompsItems.PIFruitBarrelEmpty',
	['PompsItems.PIPurpleBarrel'] = 'PompsItems.PIFruitBarrelEmpty',
	['PompsItems.PIRedBarrel'] = 'PompsItems.PIFruitBarrelEmpty',
	['PompsItems.PIWingSauceBuffalo'] = 'PompsItems.PIWingSauceBuffaloEmpty',
	['PompsItems.PIWingSauceBBQ'] = 'PompsItems.PIWingSauceBBQEmpty',
	['PompsItems.PIWingSauceGarlicParm'] = 'PompsItems.PIWingSauceGarlicParmEmpty',
	['PompsItems.PIWingSauceSRC'] = 'PompsItems.PIWingSauceSRCEmpty',
	['PompsItems.PIWingSauceTeriyaki'] = 'PompsItems.PIWingSauceTeriyakiEmpty',
	['PompsItems.PIWingSauceHoneyMustard'] = 'PompsItems.PIWingSauceHoneyMustardEmpty',
	['PompsItems.PIWingSauceHoneyBBQ'] = 'PompsItems.PIWingSauceHoneyBBQEmpty',
	['PompsItems.PIRyeWhiskey'] = 'PompsItems.PIRyeWhiskeyEmpty',
	['PompsItems.PIBottledUnsweetTea'] = 'PompsItems.PIBottledUnsweetTeaEmpty',
	['PompsItems.PIBottledTeaSweet'] = 'PompsItems.PIBottledTeaSweetEmpty',
	['PompsItems.PIBottledTeaLemon'] = 'PompsItems.PIBottledTeaLemonEmpty',
	['PompsItems.PIBottledTeaRaspberry'] = 'PompsItems.PIBottledTeaRaspberryEmpty',
	['PompsItems.PIBottledTeaExtraSweet'] = 'PompsItems.PIBottledTeaExtraSweetEmpty',
	['PompsItems.PIBottledTeaPeach'] = 'PompsItems.PIBottledTeaPeachEmpty',
	['PompsItems.PIBottledTeaGreenTea'] = 'PompsItems.PIBottledTeaGreenTeaEmpty',
	['PompsItems.PISweetTea'] = 'PompsItems.PISweetTeaEmpty',
	['PompsItems.WildPegasus'] = 'PompsItems.PegasusEmpty',
	['PompsItems.PIIslandChips'] = 'PompsItems.PIIslandChipsEmpty',
} 
Events.OnInitGlobalModData.Add(function()
    if not SandboxVars.PompsItems.Littering then
        for k,v in pairs(trashItems) do
            local item = ScriptManager.instance:getItem(k)
            if item then
                item:setReplaceOnUse(v)
            end
        end
    end
end)