-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["pert_grime_01_72"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_grime_01_73", "pert_grime_01_74", "pert_grime_01_74", "pert_grime_01_75", "pert_grime_01_76", "pert_grime_01_77"} }}
overlayMap["pert_grime_01_80"] = {{ name = "other", chance = 2, usage = "", tiles = {"pert_grime_01_81", "pert_grime_01_82", "pert_grime_01_83", "pert_grime_01_84", "pert_grime_01_85"} }}
overlayMap["pert_grime_01_88"] = {{ name = "other", chance = 1, usage = "", tiles = {"pert_grime_01_89", "pert_grime_01_90", "pert_grime_01_91", "pert_grime_01_92", "pert_grime_01_93"} }}

if not TILEZED then
	getTileOverlays():addOverlays(overlayMap)
end

return overlayMap
