require "Items/ProceduralDistributions"
-- W460NormalTire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460NormalTire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460NormalTire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460NormalTire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460NormalTire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460NormalTire2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- W460WideTire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460WideTire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460WideTire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460WideTire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460WideTire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460WideTire2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- W460Bodykit1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460Bodykit1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460Bodykit1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460Bodykit1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460Bodykit1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460Bodykit1_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- W460EngineDoor2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460EngineDoor2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460EngineDoor2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460EngineDoor2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460EngineDoor2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460EngineDoor2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- W460Bullbar2_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460Bullbar2_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460Bullbar2_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460Bullbar2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460Bullbar2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460Bullbar2_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- W460Mudflaps1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.W460Mudflaps1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.W460Mudflaps1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.W460Mudflaps1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.W460Mudflaps1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.W460Mudflaps1_Item");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);