require "Items/ProceduralDistributions"
-- KZ1Kmuffler
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1Kmuffler");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1Kmuffler");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1Kmuffler");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1Kmuffler");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1Kmuffler");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- KZ1KoldTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1KoldTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1KoldTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1KoldTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1KoldTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1KoldTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- KZ1KnormalTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1KnormalTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1KnormalTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1KnormalTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1KnormalTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1KnormalTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- KZ1KmodernTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1KmodernTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1KmodernTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1KmodernTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1KmodernTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1KmodernTire");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- KZ1KgasTank
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1KgasTank");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1KgasTank");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1KgasTank");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1KgasTank");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1KgasTank");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- KZ1Kseat
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.KZ1Kseat");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.KZ1Kseat");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.KZ1Kseat");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.KZ1Kseat");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.KZ1Kseat");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- Hat_CHiPsHelmet
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.Hat_CHiPsHelmet");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.Hat_CHiPsHelmet");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.Hat_CHiPsHelmet");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);