local group = AttachedLocations.getGroup("Human")
group:getOrCreateLocation("SlingRifle"):setAttachmentName("sling_rifle")
group:getOrCreateLocation("SlingRifle2"):setAttachmentName("sling_rifle2")
group:getOrCreateLocation("SlingRifle3"):setAttachmentName("sling_rifle3")
group:getOrCreateLocation("SlingRifle Back"):setAttachmentName("sling_rifleback")
group:getOrCreateLocation("SlingRifleBag"):setAttachmentName("sling_riflebag")

group:getOrCreateLocation("SlingWeapon"):setAttachmentName("sling_weapon")
group:getOrCreateLocation("SlingWeapon2"):setAttachmentName("sling_weapon2")
group:getOrCreateLocation("SlingWeapon3"):setAttachmentName("sling_weapon3")
group:getOrCreateLocation("SlingWeapon Back"):setAttachmentName("sling_weaponback")
group:getOrCreateLocation("SlingWeaponBag"):setAttachmentName("sling_weaponbag")
group:getOrCreateLocation("SlingBladeBag"):setAttachmentName("sling_bladebag")

group:getOrCreateLocation("SlingShovel"):setAttachmentName("sling_shovel")
group:getOrCreateLocation("SlingShovel2"):setAttachmentName("sling_shovel2")
group:getOrCreateLocation("SlingShovel3"):setAttachmentName("sling_shovel3")
group:getOrCreateLocation("SlingShovel Back"):setAttachmentName("sling_shovelback")
group:getOrCreateLocation("SlingShovelBag"):setAttachmentName("sling_shovelbag")