-- local function testFunction()
--     EggonsMU.functions.getMainInventoryItems()
-- end
-- local function keyPressedHandler(key)
--     -- print("key: ", key)
--     if key ~= 156 then -- 156 = ENTER
--         return
--     end
--     testFunction()
-- end
-- Events.OnKeyPressed.Add(keyPressedHandler)
