require "Items/ProceduralDistributions"
-- 89trooperTire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.89trooperTire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89trooperTire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89trooperTire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.89trooperTire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.89trooperTire2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- 89trooperBullbarFrontA
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.89trooperBullbarFrontA");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89trooperBullbarFrontA");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89trooperBullbarFrontA");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.89trooperBullbarFrontA");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.89trooperBullbarFrontA");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- 89trooperMudflaps2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.89trooperMudflaps2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89trooperMudflaps2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89trooperMudflaps2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.89trooperMudflaps2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- 89trooperSideSteps2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.89trooperSideSteps2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.89trooperSideSteps2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.89trooperSideSteps2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.89trooperSideSteps2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);