require "Items/ProceduralDistributions"
-- 82JeepJ10BumperFront
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.82JeepJ10BumperFront");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.82JeepJ10BumperFront");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.82JeepJ10BumperFront");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- 82JeepJ10BumperRear
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.82JeepJ10BumperRear");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.82JeepJ10BumperRear");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.82JeepJ10BumperRear");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- 82JeepJ10Windshield2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.82JeepJ10Windshield2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.82JeepJ10Windshield2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.82JeepJ10Windshield2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);