require "Items/ProceduralDistributions"
-- 69miniTire1
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.69miniTire1");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.69miniTire1");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.69miniTire1");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.69miniTire1");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.69miniTire1");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.2);
-- 69miniMeatballBulldog
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "Base.69miniMeatballBulldog");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.69miniMeatballBulldog");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.05);
table.insert(ProceduralDistributions.list["CrateToys"].items, "Base.69miniMeatballBulldog");
table.insert(ProceduralDistributions.list["CrateToys"].items, 0.05);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.69miniMeatballBulldog");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- 69miniCrateOfTea
table.insert(ProceduralDistributions.list["GigamartDryGoods"].items, "Base.69miniCrateOfTea");
table.insert(ProceduralDistributions.list["GigamartDryGoods"].items, 0.1);
table.insert(ProceduralDistributions.list["GroceryStorageCrate1"].items, "Base.69miniCrateOfTea");
table.insert(ProceduralDistributions.list["GroceryStorageCrate1"].items, 0.1);