require "Items/ProceduralDistributions"
-- ECTO1tire2_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ECTO1tire2_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ECTO1tire2_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ECTO1tire2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ECTO1tire2_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.2);
-- ECTO1tire1_Item
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ECTO1tire1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.ECTO1tire1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.ECTO1tire1_Item");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- ECTO1Bullbar1_Item
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.ECTO1Bullbar1_Item");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ECTO1Bullbar1_Item");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
-- ECTO1CarSeatrr2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.ECTO1CarSeatrr2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);