require "Items/ProceduralDistributions"
-- 90pierceArrowTire2
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.90pierceArrowTire2");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.90pierceArrowTire2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.90pierceArrowTire2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.90pierceArrowTire2");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);