require 'Items/ProceduralDistributions'

local function preDistributionMerge()

	if not SandboxVars.STR.DuffelLoot then
		ProceduralDistributions.list.LockerRosewoodSD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Brown_Dark", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Rosewood", 2,
				"STR.Hat_Police_Rosewood", 4,
				"STR.Jacket_Police_Rosewood", 4,
				"STR.Shirt_Police_Rosewood", 8,
				"STR.TShirt_Police_Rosewood", 8,
				"STR.Trousers_Police_Rosewood", 6,
				"STR.Tie_Full_Police_Rosewood", 2,
				"STR.Tie_Worn_Police_Rosewood", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerMuldraughPD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Black", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Muldraugh", 2,
				"STR.Hat_Police_Muldraugh", 4,
				"STR.Jacket_Police_Muldraugh", 4,
				"STR.Shirt_Police_Muldraugh", 8,
				"STR.TShirt_Police_Muldraugh", 8,
				"STR.Trousers_Police_Muldraugh", 6,
				"STR.Tie_Full_Police_Muldraugh", 2,
				"STR.Tie_Worn_Police_Muldraugh", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerMeadeSO = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Meade", 1.5,
				"STR.Hat_Riot_Helmet_Brown", 1.5,
				"STR.Hat_Riot_Helmet_Brown_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Meade", 2,
				"STR.Hat_Police_Meade", 4,
				"STR.Jacket_Police_Meade", 4,
				"STR.Shirt_Police_Meade", 8,
				"STR.TShirt_Police_Meade", 8,
				"STR.Trousers_Police_Meade", 6,
				"STR.Tie_Full_Police_Meade", 2,
				"STR.Tie_Worn_Police_Meade", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerWestPointPD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Navy", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_WestPoint", 2,
				"STR.Hat_Police_WestPoint", 4,
				"STR.Jacket_Police_WestPoint", 4,
				"STR.Shirt_Police_WestPoint", 8,
				"STR.TShirt_Police_WestPoint", 8,
				"STR.Trousers_Police_WestPoint", 6,
				"STR.Tie_Full_Police_WestPoint", 2,
				"STR.Tie_Worn_Police_WestPoint", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerRiversidePD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Blue", 1.5,
				"STR.Hat_Riot_Helmet_Blue_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Riverside", 2,
				"STR.Hat_Police_Riverside", 4,
				"STR.Jacket_Police_Riverside", 4,
				"STR.Shirt_Police_Riverside", 8,
				"STR.TShirt_Police_Riverside", 8,
				"STR.Trousers_Police_Riverside", 6,
				"STR.Tie_Full_Police_Riverside", 2,
				"STR.Tie_Worn_Police_Riverside", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerLouisvillePD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Louisville", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Louisville", 2,
				"STR.Hat_Police_Louisville", 4,
				"STR.Jacket_Police_Louisville", 4,
				"STR.Shirt_Police_Louisville", 8,
				"STR.TShirt_Police_Louisville", 8,
				"STR.Trousers_Police_Louisville", 6,
				"STR.Tie_Full_Police_Louisville", 2,
				"STR.Tie_Worn_Police_Louisville", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerJeffersonPD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Navy_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Jefferson", 2,
				"STR.Hat_Police_JeffersonPD", 4,
				"STR.Jacket_Police_JeffersonPD", 4,
				"STR.Shirt_Police_JeffersonPD", 8,
				"STR.TShirt_Police_JeffersonPD", 8,
				"STR.Trousers_Police_JeffersonPD", 6,
				"STR.Tie_Full_Police_Jefferson", 2,
				"STR.Tie_Worn_Police_Jefferson", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerJeffersonSD = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Brown_Dark_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Sheriff_Jefferson", 2,
				"STR.Hat_Police_JeffersonSD", 4,
				"STR.Jacket_Police_JeffersonSD", 4,
				"STR.Shirt_Police_JeffersonSD", 8,
				"STR.TShirt_Police_JeffersonSD", 8,
				"STR.Trousers_Police_JeffersonSD", 6,
				"STR.Tie_Full_Sheriff_Jefferson", 2,
				"STR.Tie_Worn_Sheriff_Jefferson", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerKSP = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Grey", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_KSP", 2,
				"STR.Hat_PoliceKSP", 4,
				"STR.Jacket_PoliceKSP", 4,
				"STR.Shirt_PoliceKSP", 8,
				"STR.TShirt_PoliceKSP", 8,
				"STR.Trousers_PoliceKSP_Summer", 6,
				"STR.Trousers_PoliceKSP_Winter", 6,
				"STR.Tie_Full_KSP", 2,
				"STR.Tie_Worn_KSP", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LaundryInmateMeade = {
			rolls = 1,
			items = {
				"STR.Boilersuit_MeadeGenPopPrisoner", 50,
				"STR.Boilersuit_MeadeGenPopPrisoner", 40,
				"STR.Boilersuit_MeadeLowRiskPrisoner", 15,
				"STR.Boilersuit_MeadeLowRiskPrisoner", 15,
				"STR.Boilersuit_MeadeMaxPrisoner", 10,
				"STR.Boilersuit_MeadeMaxPrisoner", 10,

			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.PrisonCellMeadeRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_MeadeGenPopPrisoner", 80,
					"STR.Boilersuit_MeadeLowRiskPrisoner", 40,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.PrisonCellMeadeMaxRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_MeadeMaxPrisoner", 80,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.LockerMeadeDOC = {
			rolls = 4,
			items = {
				"Glasses_Aviators", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.WalkieTalkie4", 1,
				"Radio.WalkieTalkie5", 0.5,
				"Shoes_Black", 8,
				"Shoes_Brown", 8,
				"STR.Hat_BaseballCap_DOC_Meade", 4,
				"STR.Jacket_DOC_Meade", 4,
				"STR.Shirt_DOC_Meade", 10,
				"STR.TShirt_DOC_Meade", 10,
				"STR.Trousers_DOC_Meade", 10,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LaundryInmateLouisville = {
			rolls = 1,
			items = {
				"STR.Boilersuit_JeffersonPrisoner", 50,
				"STR.Boilersuit_JeffersonPrisoner", 40,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.PrisonCellLouisvilleRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_JeffersonPrisoner", 80,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.FireStorageOutfitRW = {
			rolls = 4,
			items = {
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"LongJohns", 2,
				"LongJohns", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Long", 6,
				"Socks_Long", 6,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Meade_White", 2,
				"STR.Hat_Fireman_Meade_Black", 2,
				"STR.Hat_Fireman_Meade_Red", 2,
				"STR.Hat_Fireman_Meade_Yellow", 2,
				"STR.Hat_Fireman_Rosewood_White", 2,
				"STR.Hat_Fireman_Rosewood_Black", 2,
				"STR.Hat_Fireman_Rosewood_Red", 2,
				"STR.Hat_Fireman_Rosewood_Yellow", 2,
				"STR.Jacket_Fireman_Meade_Black", 4,
				"STR.Jacket_Fireman_Meade_Khaki", 4,
				"STR.Jacket_Fireman_Rosewood_Black", 4,
				"STR.Jacket_Fireman_Rosewood_Khaki", 4,
				"STR.Trousers_Fireman_Meade_Black", 6,
				"STR.Trousers_Fireman_Meade_Khaki", 6,
				"STR.Trousers_Fireman_Rosewood_Black", 6,
				"STR.Trousers_Fireman_Rosewood_Khaki", 6,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.FireDeptLockersRW = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_GasMask", 0.5,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shirt_Denim", 8,
				"Shirt_Lumberjack", 6,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Ankle", 8,
				"Socks_Long", 6,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Trousers_Fire_Formal_Meade", 3,
				"STR.Trousers_Fire_Formal_Rosewood", 3,
				"STR.Shirt_Fire_Meade", 2,
				"STR.TShirt_Fire_Meade", 2,
				"STR.Shirt_Fire_Supervisor_Meade", 2,
				"STR.TShirt_Fire_Supervisor_Meade", 2,
				"STR.Shirt_Fire_Rosewood", 2,
				"STR.TShirt_Fire_Rosewood", 2,
				"STR.Shirt_Fire_Supervisor_Rosewood", 2,
				"STR.TShirt_Fire_Supervisor_Rosewood", 2,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Meade_White", 2,
				"STR.Hat_Fireman_Meade_Black", 2,
				"STR.Hat_Fireman_Meade_Red", 2,
				"STR.Hat_Fireman_Meade_Yellow", 2,
				"STR.Hat_Fireman_Rosewood_White", 2,
				"STR.Hat_Fireman_Rosewood_Black", 2,
				"STR.Hat_Fireman_Rosewood_Red", 2,
				"STR.Hat_Fireman_Rosewood_Yellow", 2,
				"STR.Jacket_Fireman_Meade_Black", 4,
				"STR.Jacket_Fireman_Meade_Khaki", 4,
				"STR.Jacket_Fireman_Rosewood_Black", 4,
				"STR.Jacket_Fireman_Rosewood_Khaki", 4,
				"STR.Trousers_Fireman_Meade_Black", 6,
				"STR.Trousers_Fireman_Meade_Khaki", 6,
				"STR.Trousers_Fireman_Rosewood_Black", 6,
				"STR.Trousers_Fireman_Rosewood_Khaki", 6,
				"STR.TShirt_Profession_FiremanBlue_Meade", 6,
				"STR.TShirt_Profession_FiremanRed_Meade", 6,
				"STR.TShirt_Profession_FiremanRed_Meade02", 6,
				"STR.TShirt_Profession_FiremanWhite_Meade", 6,
				"STR.TShirt_Profession_FiremanBlue_Rosewood", 6,
				"STR.TShirt_Profession_FiremanRed_Rosewood", 6,
				"STR.TShirt_Profession_FiremanRed_Rosewood02", 6,
				"STR.TShirt_Profession_FiremanWhite_Rosewood", 6,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.FireDeptLockersLV = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_GasMask", 0.5,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shirt_Denim", 8,
				"Shirt_Lumberjack", 6,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Ankle", 8,
				"Socks_Long", 6,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_Fire_Louisville", 0.5,
				"STR.Tie_Worn_Fire_Louisville", 0.5,
				"STR.Hat_Fire_Louisville", 1,
				"STR.Hat_Fire_Supervisor_Louisville", 1,
				"STR.Jacket_Dress_Fire_Louisville", 2,
				"STR.Trousers_Fire_Formal_Louisville", 3,
				"STR.Shirt_Fire_Supervisor_Formal_Louisville", 1,
				"STR.TShirt_Fire_Supervisor_Formal_Louisville", 1,
				"STR.Shirt_Fire_Supervisor_Louisville", 2,
				"STR.TShirt_Fire_Supervisor_Louisville", 2,
				"STR.Shirt_Fire_Louisville", 2,
				"STR.TShirt_Fire_Louisville", 2,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Louisville_Blue", 2,
				"STR.Hat_Fireman_Louisville_White", 2,
				"STR.Hat_Fireman_Louisville_Black", 2,
				"STR.Hat_Fireman_Louisville_Red", 2,
				"STR.Hat_Fireman_Louisville_Yellow", 2,
				"STR.Jacket_Fireman_Louisville_Black", 4,
				"STR.Jacket_Fireman_Louisville_Khaki", 4,
				"STR.Trousers_Fireman_Louisville_Black", 6,
				"STR.Trousers_Fireman_Louisville_Khaki", 6,
				"STR.TShirt_Profession_FiremanBlue_Louisville", 8,
				"STR.TShirt_Profession_FiremanRed_Louisville", 8,
				"STR.TShirt_Profession_FiremanRed_Louisville02", 8,
				"STR.TShirt_Profession_FiremanWhite_Louisville", 8,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockersMeadeEMS = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Meade", 0.5,
				"STR.Tie_Worn_EMS_Meade", 0.5,
				"STR.Hat_EMS_Meade", 1,
				"STR.Jacket_Dress_EMS_Meade", 2,
				"STR.Hat_BaseballCap_EMS_Meade", 4,
				"STR.Jacket_EMS_Meade", 4,
				"STR.Shirt_EMS_Meade", 10,
				"STR.TShirt_EMS_Meade", 10,
				"STR.Trousers_EMS_Meade", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersLouisvilleEMS = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Louisville", 0.5,
				"STR.Tie_Worn_EMS_Louisville", 0.5,
				"STR.Hat_EMS_Louisville", 1,
				"STR.Jacket_Dress_EMS_Louisville", 2,
				"STR.Hat_BaseballCap_EMS_Louisville", 4,
				"STR.Jacket_EMS_Louisville", 4,
				"STR.Shirt_EMS_Louisville", 10,
				"STR.TShirt_EMS_Louisville", 10,
				"STR.Trousers_EMS_Louisville", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersJeffersonEMS = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Jefferson", 0.5,
				"STR.Tie_Worn_EMS_Jefferson", 0.5,
				"STR.Hat_EMS_Jefferson", 1,
				"STR.Jacket_Dress_EMS_Jefferson", 2,
				"STR.Hat_BaseballCap_EMS_Jefferson", 4,
				"STR.Jacket_EMS_Jefferson", 4,
				"STR.Shirt_EMS_Jefferson", 10,
				"STR.TShirt_EMS_Jefferson", 10,
				"STR.Trousers_EMS_Jefferson", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersUSPSHQ = {
			rolls = 4,
			items = {
				"Bag_DuffelBagTINT", 0.2,
				"Bag_FannyPackFront", 0.6,
				"Belt2", 2,
				"Briefcase", 0.1,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.1,
				"STR.Hat_BaseballCap_USPS", 4,
				"STR.Jacket_USPS", 4,
				"STR.Shirt_USPS", 8,
				"STR.TShirt_USPS", 8,
				"STR.Trousers_USPS", 6,
				"STR.Shorts_USPS", 6,
				"STR.Shorts_ShortUSPS", 6,
				"STR.Bag_Satchel_USPS", 4,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.AllMetalShelves = {
			rolls = 4,
			items = {
				"BallPeenHammer", 0.6,
				"Battery", 1,
				"BucketEmpty", 0.4,
				"ClubHammer", 0.4,
				"Crowbar", 0.4,
				"DuctTape", 0.8,
				"Glasses_SafetyGoggles", 0.2,
				"Hammer", 0.6,
				"HandAxe", 0.1,
				"HandTorch", 0.4,
				"Hat_DustMask", 0.2,
				"Hat_HardHat", 0.1,
				"LeadPipe", 0.4,
				"LeadPipe", 0.4,
				"MetalBar", 1.2,
				"MetalPipe", 2,
				"Nails", 4,
				"NailsBox", 1,
				"PipeWrench", 0.4,
				"Radio.ElectricWire", 0.5,
				"Radio.RadioBlack", 2,
				"Radio.RadioRed", 1,
				"Radio.WalkieTalkie1", 0.05,
				"Radio.WalkieTalkie2", 0.03,
				"Radio.WalkieTalkie3", 0.01,
				"Rope", 0.8,
				"Saw", 0.4,
				"Screwdriver", 1,
				"ScrewsBox", 0.4,
				"SheetMetal", 2,
				"Shovel", 0.4,
				"Shovel2", 0.4,
				"SmallSheetMetal", 1,
				"Tarp", 1,
				"Toolbox", 0.5,
				"Torch", 0.2,
				"Twine", 1,
				"WeldingMask", 0.2,
				"WeldingRods", 1,
				"Wire", 0.8,
				"WoodenMallet", 0.4,
				"Woodglue", 0.4,
				"Wrench", 0.6,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.AllCrate = {
			rolls = 1,
			items = {
                "Axe", 0.005,
                "BallPeenHammer", 0.6,
                "BarbedWire", 0.2,
                "Battery", 1,
                "BlowTorch", 0.8,
                "BucketEmpty", 0.4,
                "camping.TentPeg", 2,
                "Charcoal", 0.05,
                "ClubHammer", 0.4,
                "ConcretePowder", 2,
                "Crowbar", 0.4,
                "DuctTape", 0.8,
                "EmptySandbag", 0.2,
                "farming.BroccoliBagSeed", 0.8,
                "farming.CabbageBagSeed", 0.8,
                "farming.CarrotBagSeed", 0.8,
                "farming.GardeningSprayEmpty", 0.6,
                "farming.HandShovel", 1,
                "farming.PotatoBagSeed", 0.8,
                "farming.RedRadishBagSeed", 0.8,
                "farming.StrewberrieBagSeed", 0.8,
                "farming.TomatoBagSeed", 0.8,
                "farming.WateredCan", 0.6,
                "Fertilizer", 2,
                "GardenFork", 0.1,
                "GardenHoe", 0.2,
                "GardenSaw", 0.6,
                "Glasses_SafetyGoggles", 0.2,
                "Gravelbag", 2,
                "Hammer", 0.6,
                "HandAxe", 0.1,
                "HandFork", 0.2,
                "HandScythe", 0.2,
                "HandTorch", 0.4,
                "Hat_DustMask", 0.2,
                "Hat_HardHat", 0.1,
                "Jack", 0.2,
                "LeadPipe", 0.4,
                "LeafRake", 1,
                "Lighter", 4,
                "LugWrench", 0.9,
                "MetalBar", 1.2,
                "MetalPipe", 2,
                "NailsBox", 1,
                "NailsBox", 1,
                "NailsBox", 1,
                "NailsBox", 1,
                "PaintBlack", 0.8,
                "PaintBlue", 0.8,
                "PaintBrown", 0.8,
                "Paintbrush", 0.4,
                "PaintCyan", 0.8,
                "PaintGreen", 0.8,
                "PaintGrey", 0.8,
                "PaintLightBlue", 0.8,
                "PaintLightBrown", 0.8,
                "PaintOrange", 0.8,
                "PaintPink", 0.8,
                "PaintPurple", 0.8,
                "PaintRed", 0.8,
                "PaintTurquoise",0.8,
                "PaintWhite", 0.8,
                "PaintYellow", 0.8,
                "Paperclip", 0.8,
                "PaperclipBox", 0.5,
                "PickAxe", 0.05,
                "PipeWrench", 0.4,
                "Plank", 1,
                "Plank", 1,
                "PlasterPowder", 2,
                "PropaneTank", 0.05,
                "Radio.ElectricWire", 0.5,
                "Radio.HamRadio1", 0.005,
                "Radio.RadioBlack", 2,
                "Radio.RadioRed", 1,
                "Radio.WalkieTalkie1", 0.05,
                "Radio.WalkieTalkie2", 0.03,
                "Radio.WalkieTalkie3", 0.01,
                "Rake", 1,
                "Rope", 0.8,
                "Sandbag", 0.5,
                "Saw", 0.4,
                "Screwdriver", 1,
                "ScrewsBox", 0.4,
                "SheetMetal", 2,
                "Shovel", 0.4,
                "Shovel2", 0.4,
                "Sledgehammer", 0.001,
                "Sledgehammer2", 0.001,
                "SmallSheetMetal", 1,
                "Tarp", 1,
                "TirePump", 0.6,
                "Torch", 0.2,
                "Twine", 1,
                "WeldingMask", 0.2,
                "WeldingRods", 1,
                "Wire", 0.8,
                "WoodAxe", 0.0025,
                "WoodenMallet", 0.4,
                "Woodglue", 0.4,
                "Wrench", 0.6,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockerOhioMall = {
			rolls = 4,
			items = {
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"HandTorch", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Security_Mall_Ohio", 3,
				"STR.Jacket_Security_Mall_Ohio", 3,
				"STR.Shirt_Security_Mall_Ohio", 6,
				"STR.TShirt_Security_Mall_Ohio", 6,
				"STR.Trousers_Security_Mall_Ohio", 4,
				"STR.Tie_Full_Security_Mall_Ohio", 2,
				"STR.Tie_Worn_Security_Mall_Ohio", 2,
				"STR.Belt_PoliceDuty", 2,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerValleyMall = {
			rolls = 4,
			items = {
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"HandTorch", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Security_Mall_Valley", 3,
				"STR.Jacket_Security_Mall_Valley", 3,
				"STR.Shirt_Security_Mall_Valley", 6,
				"STR.TShirt_Security_Mall_Valley", 6,
				"STR.Trousers_Security_Mall_Valley", 4,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

	elseif SandboxVars.STR.DuffelLoot then
		ProceduralDistributions.list.LockerRosewoodSD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Brown_Dark", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Rosewood", 2,
				"STR.Bag_DuffelBag_Police_Rosewood", 1,
				"STR.Hat_Police_Rosewood", 4,
				"STR.Jacket_Police_Rosewood", 4,
				"STR.Shirt_Police_Rosewood", 8,
				"STR.TShirt_Police_Rosewood", 8,
				"STR.Trousers_Police_Rosewood", 6,
				"STR.Tie_Full_Police_Rosewood", 2,
				"STR.Tie_Worn_Police_Rosewood", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerMuldraughPD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Black", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Muldraugh", 2,
				"STR.Bag_DuffelBag_Police_Black", 0.5,
				"STR.Bag_DuffelBag_Police_Navy", 0.5,
				"STR.Bag_DuffelBag_Police_Olive", 0.5,
				"STR.Hat_Police_Muldraugh", 4,
				"STR.Jacket_Police_Muldraugh", 4,
				"STR.Shirt_Police_Muldraugh", 8,
				"STR.TShirt_Police_Muldraugh", 8,
				"STR.Trousers_Police_Muldraugh", 6,
				"STR.Tie_Full_Police_Muldraugh", 2,
				"STR.Tie_Worn_Police_Muldraugh", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerMeadeSO = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Meade", 1.5,
				"STR.Hat_Riot_Helmet_Brown", 1.5,
				"STR.Hat_Riot_Helmet_Brown_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Meade", 2,
				"STR.Bag_DuffelBag_Police_Meade", 1,
				"STR.Hat_Police_Meade", 4,
				"STR.Jacket_Police_Meade", 4,
				"STR.Shirt_Police_Meade", 8,
				"STR.TShirt_Police_Meade", 8,
				"STR.Trousers_Police_Meade", 6,
				"STR.Tie_Full_Police_Meade", 2,
				"STR.Tie_Worn_Police_Meade", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerWestPointPD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Navy", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_WestPoint", 2,
				"STR.Bag_DuffelBag_Police_Black", 0.5,
				"STR.Bag_DuffelBag_Police_Navy", 0.5,
				"STR.Bag_DuffelBag_Police_Olive", 0.5,
				"STR.Hat_Police_WestPoint", 4,
				"STR.Jacket_Police_WestPoint", 4,
				"STR.Shirt_Police_WestPoint", 8,
				"STR.TShirt_Police_WestPoint", 8,
				"STR.Trousers_Police_WestPoint", 6,
				"STR.Tie_Full_Police_WestPoint", 2,
				"STR.Tie_Worn_Police_WestPoint", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerRiversidePD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Blue", 1.5,
				"STR.Hat_Riot_Helmet_Blue_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Riverside", 2,
				"STR.Bag_DuffelBag_Police_Black", 0.5,
				"STR.Bag_DuffelBag_Police_Navy", 0.5,
				"STR.Bag_DuffelBag_Police_Olive", 0.5,
				"STR.Hat_Police_Riverside", 4,
				"STR.Jacket_Police_Riverside", 4,
				"STR.Shirt_Police_Riverside", 8,
				"STR.TShirt_Police_Riverside", 8,
				"STR.Trousers_Police_Riverside", 6,
				"STR.Tie_Full_Police_Riverside", 2,
				"STR.Tie_Worn_Police_Riverside", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerLouisvillePD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Louisville", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Louisville", 2,
				"STR.Bag_DuffelBag_Police_Black", 0.5,
				"STR.Bag_DuffelBag_Police_Navy", 0.5,
				"STR.Bag_DuffelBag_Police_Olive", 0.5,
				"STR.Hat_Police_Louisville", 4,
				"STR.Jacket_Police_Louisville", 4,
				"STR.Shirt_Police_Louisville", 8,
				"STR.TShirt_Police_Louisville", 8,
				"STR.Trousers_Police_Louisville", 6,
				"STR.Tie_Full_Police_Louisville", 2,
				"STR.Tie_Worn_Police_Louisville", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerJeffersonPD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Navy_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_Jefferson", 2,
				"STR.Bag_DuffelBag_Police_Black", 0.5,
				"STR.Bag_DuffelBag_Police_Navy", 0.5,
				"STR.Bag_DuffelBag_Police_Olive", 0.5,
				"STR.Hat_Police_JeffersonPD", 4,
				"STR.Jacket_Police_JeffersonPD", 4,
				"STR.Shirt_Police_JeffersonPD", 8,
				"STR.TShirt_Police_JeffersonPD", 8,
				"STR.Trousers_Police_JeffersonPD", 6,
				"STR.Tie_Full_Police_Jefferson", 2,
				"STR.Tie_Worn_Police_Jefferson", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerJeffersonSD = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Brown_Dark_Stripe", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Sheriff_Jefferson", 2,
				"STR.Bag_DuffelBag_Police_Meade", 1,
				"STR.Hat_Police_JeffersonSD", 4,
				"STR.Jacket_Police_JeffersonSD", 4,
				"STR.Shirt_Police_JeffersonSD", 8,
				"STR.TShirt_Police_JeffersonSD", 8,
				"STR.Trousers_Police_JeffersonSD", 6,
				"STR.Tie_Full_Sheriff_Jefferson", 2,
				"STR.Tie_Worn_Sheriff_Jefferson", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"STR.Vest_BulletPolice_Meade", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerKSP = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_CrashHelmet_Police", 1,
				"Hat_EarMuff_Protectors", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Riot_Helmet_Grey", 1.5,
				"STR.Gloves_Leather_Black", 2,
				"STR.Gloves_Leather_Brown", 2,
				"STR.Gloves_Dress_White", 1,
				"STR.Jacket_Dress_Police_KSP", 2,
				"STR.Bag_DuffelBag_Police_KSP", 1,
				"STR.Hat_PoliceKSP", 4,
				"STR.Jacket_PoliceKSP", 4,
				"STR.Shirt_PoliceKSP", 8,
				"STR.TShirt_PoliceKSP", 8,
				"STR.Trousers_PoliceKSP_Summer", 6,
				"STR.Trousers_PoliceKSP_Winter", 6,
				"STR.Tie_Full_KSP", 2,
				"STR.Tie_Worn_KSP", 2,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
				"Vest_BulletPolice", 1,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LaundryInmateMeade = {
			rolls = 1,
			items = {
				"STR.Boilersuit_MeadeGenPopPrisoner", 50,
				"STR.Boilersuit_MeadeGenPopPrisoner", 40,
				"STR.Boilersuit_MeadeLowRiskPrisoner", 15,
				"STR.Boilersuit_MeadeLowRiskPrisoner", 15,
				"STR.Boilersuit_MeadeMaxPrisoner", 10,
				"STR.Boilersuit_MeadeMaxPrisoner", 10,

			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.PrisonCellMeadeRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_MeadeGenPopPrisoner", 80,
					"STR.Boilersuit_MeadeLowRiskPrisoner", 40,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.PrisonCellMeadeMaxRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_MeadeMaxPrisoner", 80,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.LockerMeadeDOC = {
			rolls = 4,
			items = {
				"Glasses_Aviators", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.WalkieTalkie4", 1,
				"Radio.WalkieTalkie5", 0.5,
				"Shoes_Black", 8,
				"Shoes_Brown", 8,
				"STR.Hat_BaseballCap_DOC_Meade", 4,
				"STR.Jacket_DOC_Meade", 4,
				"STR.Shirt_DOC_Meade", 10,
				"STR.TShirt_DOC_Meade", 10,
				"STR.Trousers_DOC_Meade", 10,
				"STR.Belt_PoliceDuty", 2,
				"STR.Chest_Walkie", 2,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LaundryInmateLouisville = {
			rolls = 1,
			items = {
				"STR.Boilersuit_JeffersonPrisoner", 50,
				"STR.Boilersuit_JeffersonPrisoner", 40,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.PrisonCellLouisvilleRandom = {
			rolls = 4,
			items = {
				"Antibiotics", 0.25,
				"Bandage", 0.25,
				"Radio.CDplayer", 1,
				"Cereal", 4,
				"Chocolate", 4,
				"CordlessPhone", 0.01,
				"Crisps", 10,
				"HottieZ", 0.01,
				"Magazine", 10,
				"Newspaper", 10,
				"Notebook", 10,
				"Pencil", 10,
				"Pills", 0.5,
				"Radio.RadioBlack", 1,
				"Ramen", 10,
				"SheetPaper2", 20,
				"Teabag2", 6,
				"TunaTin", 4,
				"WhiskeyFull", 0.01,
			},
			junk = {
				rolls = 1,
				items = {
					"BathTowel", 20,
					"STR.Boilersuit_JeffersonPrisoner", 80,
					"Bowl", 10,
					"ButterKnife", 0.05,
					"Cigarettes", 8,
					"Comb", 4,
					"Crayons", 8,
					"Doll", 4,
					"KitchenKnife", 0.01,
					"Lighter", 4,
					"Matches", 8,
					"Mirror", 8,
					"Mugl", 4,
					"MugRed", 4,
					"MugWhite", 4,
					"Shoes_FlipFlop", 6,
					"Soap2", 10,
					"Socks_Ankle", 4,
					"Spiffo", 0.001,
					"Spoon", 20,
					"Toothbrush", 10,
					"Toothpaste", 10,
					"ToyBear", 4,
				}
			}
		}

		ProceduralDistributions.list.FireStorageOutfitRW = {
			rolls = 4,
			items = {
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"Hat_GasMask", 1,
				"LongJohns", 2,
				"LongJohns", 2,
				"Radio.WalkieTalkie4", 1,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Long", 6,
				"Socks_Long", 6,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Meade_White", 2,
				"STR.Hat_Fireman_Meade_Black", 2,
				"STR.Hat_Fireman_Meade_Red", 2,
				"STR.Hat_Fireman_Meade_Yellow", 2,
				"STR.Hat_Fireman_Rosewood_White", 2,
				"STR.Hat_Fireman_Rosewood_Black", 2,
				"STR.Hat_Fireman_Rosewood_Red", 2,
				"STR.Hat_Fireman_Rosewood_Yellow", 2,
				"STR.Jacket_Fireman_Meade_Black", 4,
				"STR.Jacket_Fireman_Meade_Khaki", 4,
				"STR.Jacket_Fireman_Rosewood_Black", 4,
				"STR.Jacket_Fireman_Rosewood_Khaki", 4,
				"STR.Trousers_Fireman_Meade_Black", 6,
				"STR.Trousers_Fireman_Meade_Khaki", 6,
				"STR.Trousers_Fireman_Rosewood_Black", 6,
				"STR.Trousers_Fireman_Rosewood_Khaki", 6,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.FireDeptLockersRW = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_GasMask", 0.5,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shirt_Denim", 8,
				"Shirt_Lumberjack", 6,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Ankle", 8,
				"Socks_Long", 6,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Trousers_Fire_Formal_Meade", 3,
				"STR.Trousers_Fire_Formal_Rosewood", 3,
				"STR.Shirt_Fire_Meade", 2,
				"STR.TShirt_Fire_Meade", 2,
				"STR.Shirt_Fire_Supervisor_Meade", 2,
				"STR.TShirt_Fire_Supervisor_Meade", 2,
				"STR.Shirt_Fire_Rosewood", 2,
				"STR.TShirt_Fire_Rosewood", 2,
				"STR.Shirt_Fire_Supervisor_Rosewood", 2,
				"STR.TShirt_Fire_Supervisor_Rosewood", 2,
				"STR.Bag_DuffelBag_Fire_Black", 0.5,
				"STR.Bag_DuffelBag_Fire_Khaki", 0.5,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Meade_White", 2,
				"STR.Hat_Fireman_Meade_Black", 2,
				"STR.Hat_Fireman_Meade_Red", 2,
				"STR.Hat_Fireman_Meade_Yellow", 2,
				"STR.Hat_Fireman_Rosewood_White", 2,
				"STR.Hat_Fireman_Rosewood_Black", 2,
				"STR.Hat_Fireman_Rosewood_Red", 2,
				"STR.Hat_Fireman_Rosewood_Yellow", 2,
				"STR.Jacket_Fireman_Meade_Black", 4,
				"STR.Jacket_Fireman_Meade_Khaki", 4,
				"STR.Jacket_Fireman_Rosewood_Black", 4,
				"STR.Jacket_Fireman_Rosewood_Khaki", 4,
				"STR.Trousers_Fireman_Meade_Black", 6,
				"STR.Trousers_Fireman_Meade_Khaki", 6,
				"STR.Trousers_Fireman_Rosewood_Black", 6,
				"STR.Trousers_Fireman_Rosewood_Khaki", 6,
				"STR.TShirt_Profession_FiremanBlue_Meade", 6,
				"STR.TShirt_Profession_FiremanRed_Meade", 6,
				"STR.TShirt_Profession_FiremanRed_Meade02", 6,
				"STR.TShirt_Profession_FiremanWhite_Meade", 6,
				"STR.TShirt_Profession_FiremanBlue_Rosewood", 6,
				"STR.TShirt_Profession_FiremanRed_Rosewood", 6,
				"STR.TShirt_Profession_FiremanRed_Rosewood02", 6,
				"STR.TShirt_Profession_FiremanWhite_Rosewood", 6,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.FireDeptLockersLV = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Glasses_Aviators", 1,
				"Hat_GasMask", 0.5,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"Shirt_Denim", 8,
				"Shirt_Lumberjack", 6,
				"Shoes_ArmyBoots", 4,
				"Shoes_ArmyBoots", 4,
				"Socks_Ankle", 8,
				"Socks_Long", 6,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_Fire_Louisville", 0.5,
				"STR.Tie_Worn_Fire_Louisville", 0.5,
				"STR.Hat_Fire_Louisville", 1,
				"STR.Hat_Fire_Supervisor_Louisville", 1,
				"STR.Jacket_Dress_Fire_Louisville", 2,
				"STR.Trousers_Fire_Formal_Louisville", 3,
				"STR.Shirt_Fire_Supervisor_Formal_Louisville", 1,
				"STR.TShirt_Fire_Supervisor_Formal_Louisville", 1,
				"STR.Shirt_Fire_Supervisor_Louisville", 2,
				"STR.TShirt_Fire_Supervisor_Louisville", 2,
				"STR.Shirt_Fire_Louisville", 2,
				"STR.TShirt_Fire_Louisville", 2,
				"STR.Bag_DuffelBag_Fire_Black", 0.5,
				"STR.Bag_DuffelBag_Fire_Khaki", 0.5,
				"STR.Gloves_Fireman_Khaki", 2,
				"STR.Gloves_Fireman_Khaki_Simple", 2,
				"STR.Gloves_Fireman_Black", 2,
				"STR.Gloves_Fireman_Black_Simple", 2,
				"STR.Hat_Fireman_Louisville_Blue", 2,
				"STR.Hat_Fireman_Louisville_White", 2,
				"STR.Hat_Fireman_Louisville_Black", 2,
				"STR.Hat_Fireman_Louisville_Red", 2,
				"STR.Hat_Fireman_Louisville_Yellow", 2,
				"STR.Jacket_Fireman_Louisville_Black", 4,
				"STR.Jacket_Fireman_Louisville_Khaki", 4,
				"STR.Trousers_Fireman_Louisville_Black", 6,
				"STR.Trousers_Fireman_Louisville_Khaki", 6,
				"STR.TShirt_Profession_FiremanBlue_Louisville", 8,
				"STR.TShirt_Profession_FiremanRed_Louisville", 8,
				"STR.TShirt_Profession_FiremanRed_Louisville02", 8,
				"STR.TShirt_Profession_FiremanWhite_Louisville", 8,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockersMeadeEMS = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Meade", 0.5,
				"STR.Tie_Worn_EMS_Meade", 0.5,
				"STR.Hat_EMS_Meade", 1,
				"STR.Jacket_Dress_EMS_Meade", 2,
				"STR.Bag_DuffelBag_EMS_Red", 0.5,
				"STR.Bag_DuffelBag_EMS_Blue", 0.5,
				"STR.Bag_DuffelBag_EMS_Green", 0.5,
				"STR.Hat_BaseballCap_EMS_Meade", 4,
				"STR.Jacket_EMS_Meade", 4,
				"STR.Shirt_EMS_Meade", 10,
				"STR.TShirt_EMS_Meade", 10,
				"STR.Trousers_EMS_Meade", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersLouisvilleEMS = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Louisville", 0.5,
				"STR.Tie_Worn_EMS_Louisville", 0.5,
				"STR.Hat_EMS_Louisville", 1,
				"STR.Jacket_Dress_EMS_Louisville", 2,
				"STR.Bag_DuffelBag_EMS_Red", 0.5,
				"STR.Bag_DuffelBag_EMS_Blue", 0.5,
				"STR.Bag_DuffelBag_EMS_Green", 0.5,
				"STR.Hat_BaseballCap_EMS_Louisville", 4,
				"STR.Jacket_EMS_Louisville", 4,
				"STR.Shirt_EMS_Louisville", 10,
				"STR.TShirt_EMS_Louisville", 10,
				"STR.Trousers_EMS_Louisville", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersJeffersonEMS = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.5,
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.2,
				"STR.Gloves_Dress_White", 1,
				"STR.Tie_Full_EMS_Jefferson", 0.5,
				"STR.Tie_Worn_EMS_Jefferson", 0.5,
				"STR.Hat_EMS_Jefferson", 1,
				"STR.Jacket_Dress_EMS_Jefferson", 2,
				"STR.Bag_DuffelBag_EMS_Red", 0.5,
				"STR.Bag_DuffelBag_EMS_Blue", 0.5,
				"STR.Bag_DuffelBag_EMS_Green", 0.5,
				"STR.Hat_BaseballCap_EMS_Jefferson", 4,
				"STR.Jacket_EMS_Jefferson", 4,
				"STR.Shirt_EMS_Jefferson", 10,
				"STR.TShirt_EMS_Jefferson", 10,
				"STR.Trousers_EMS_Jefferson", 8,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockersUSPSHQ = {
			rolls = 4,
			items = {
				--"Bag_DuffelBagTINT", 0.2,
				"Bag_FannyPackFront", 0.6,
				"Belt2", 2,
				"Briefcase", 0.1,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Radio.CDplayer", 2,
				"Shoes_Random", 2,
				"Shoes_TrainerTINT", 2,
				"Socks_Ankle", 1,
				"Socks_Ankle", 1,
				"Socks_Long", 0.5,
				"Suitcase", 0.1,
				"STR.Bag_DuffelBag_USPS", 2,
				"STR.Hat_BaseballCap_USPS", 4,
				"STR.Jacket_USPS", 4,
				"STR.Shirt_USPS", 8,
				"STR.TShirt_USPS", 8,
				"STR.Trousers_USPS", 6,
				"STR.Shorts_USPS", 6,
				"STR.Shorts_ShortUSPS", 6,
				"STR.Bag_Satchel_USPS", 4,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.AllMetalShelves = {
			rolls = 4,
			items = {
				"BallPeenHammer", 0.6,
				"Battery", 1,
				"BucketEmpty", 0.4,
				"ClubHammer", 0.4,
				"Crowbar", 0.4,
				"DuctTape", 0.8,
				"Glasses_SafetyGoggles", 0.2,
				"Hammer", 0.6,
				"HandAxe", 0.1,
				"HandTorch", 0.4,
				"Hat_DustMask", 0.2,
				"Hat_HardHat", 0.1,
				"LeadPipe", 0.4,
				"LeadPipe", 0.4,
				"MetalBar", 1.2,
				"MetalPipe", 2,
				"Nails", 4,
				"NailsBox", 1,
				"PipeWrench", 0.4,
				"Radio.ElectricWire", 0.5,
				"Radio.RadioBlack", 2,
				"Radio.RadioRed", 1,
				"Radio.WalkieTalkie1", 0.05,
				"Radio.WalkieTalkie2", 0.03,
				"Radio.WalkieTalkie3", 0.01,
				"Rope", 0.8,
				"Saw", 0.4,
				"Screwdriver", 1,
				"ScrewsBox", 0.4,
				"SheetMetal", 2,
				"Shovel", 0.4,
				"Shovel2", 0.4,
				"SmallSheetMetal", 1,
				"Tarp", 1,
				"Toolbox", 0.5,
				"Torch", 0.2,
				"Twine", 1,
				"WeldingMask", 0.2,
				"WeldingRods", 1,
				"Wire", 0.8,
				"WoodenMallet", 0.4,
				"Woodglue", 0.4,
				"Wrench", 0.6,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.AllCrate = {
			rolls = 1,
			items = {
                "Axe", 0.005,
                "BallPeenHammer", 0.6,
                "BarbedWire", 0.2,
                "Battery", 1,
                "BlowTorch", 0.8,
                "BucketEmpty", 0.4,
                "camping.TentPeg", 2,
                "Charcoal", 0.05,
                "ClubHammer", 0.4,
                "ConcretePowder", 2,
                "Crowbar", 0.4,
                "DuctTape", 0.8,
                "EmptySandbag", 0.2,
                "farming.BroccoliBagSeed", 0.8,
                "farming.CabbageBagSeed", 0.8,
                "farming.CarrotBagSeed", 0.8,
                "farming.GardeningSprayEmpty", 0.6,
                "farming.HandShovel", 1,
                "farming.PotatoBagSeed", 0.8,
                "farming.RedRadishBagSeed", 0.8,
                "farming.StrewberrieBagSeed", 0.8,
                "farming.TomatoBagSeed", 0.8,
                "farming.WateredCan", 0.6,
                "Fertilizer", 2,
                "GardenFork", 0.1,
                "GardenHoe", 0.2,
                "GardenSaw", 0.6,
                "Glasses_SafetyGoggles", 0.2,
                "Gravelbag", 2,
                "Hammer", 0.6,
                "HandAxe", 0.1,
                "HandFork", 0.2,
                "HandScythe", 0.2,
                "HandTorch", 0.4,
                "Hat_DustMask", 0.2,
                "Hat_HardHat", 0.1,
                "Jack", 0.2,
                "LeadPipe", 0.4,
                "LeafRake", 1,
                "Lighter", 4,
                "LugWrench", 0.9,
                "MetalBar", 1.2,
                "MetalPipe", 2,
                "NailsBox", 1,
                "NailsBox", 1,
                "NailsBox", 1,
                "NailsBox", 1,
                "PaintBlack", 0.8,
                "PaintBlue", 0.8,
                "PaintBrown", 0.8,
                "Paintbrush", 0.4,
                "PaintCyan", 0.8,
                "PaintGreen", 0.8,
                "PaintGrey", 0.8,
                "PaintLightBlue", 0.8,
                "PaintLightBrown", 0.8,
                "PaintOrange", 0.8,
                "PaintPink", 0.8,
                "PaintPurple", 0.8,
                "PaintRed", 0.8,
                "PaintTurquoise",0.8,
                "PaintWhite", 0.8,
                "PaintYellow", 0.8,
                "Paperclip", 0.8,
                "PaperclipBox", 0.5,
                "PickAxe", 0.05,
                "PipeWrench", 0.4,
                "Plank", 1,
                "Plank", 1,
                "PlasterPowder", 2,
                "PropaneTank", 0.05,
                "Radio.ElectricWire", 0.5,
                "Radio.HamRadio1", 0.005,
                "Radio.RadioBlack", 2,
                "Radio.RadioRed", 1,
                "Radio.WalkieTalkie1", 0.05,
                "Radio.WalkieTalkie2", 0.03,
                "Radio.WalkieTalkie3", 0.01,
                "Rake", 1,
                "Rope", 0.8,
                "Sandbag", 0.5,
                "Saw", 0.4,
                "Screwdriver", 1,
                "ScrewsBox", 0.4,
                "SheetMetal", 2,
                "Shovel", 0.4,
                "Shovel2", 0.4,
                "Sledgehammer", 0.001,
                "Sledgehammer2", 0.001,
                "SmallSheetMetal", 1,
                "Tarp", 1,
                "TirePump", 0.6,
                "Torch", 0.2,
                "Twine", 1,
                "WeldingMask", 0.2,
                "WeldingRods", 1,
                "Wire", 0.8,
                "WoodAxe", 0.0025,
                "WoodenMallet", 0.4,
                "Woodglue", 0.4,
                "Wrench", 0.6,
			},
			junk = {
				rolls = 1,
				items = {

				}
			}
		}

		ProceduralDistributions.list.LockerOhioMall = {
			rolls = 4,
			items = {
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"HandTorch", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Security_Mall_Ohio", 3,
				"STR.Jacket_Security_Mall_Ohio", 3,
				"STR.Shirt_Security_Mall_Ohio", 6,
				"STR.TShirt_Security_Mall_Ohio", 6,
				"STR.Trousers_Security_Mall_Ohio", 4,
				"STR.Tie_Full_Security_Mall_Ohio", 2,
				"STR.Tie_Worn_Security_Mall_Ohio", 2,
				"STR.Belt_PoliceDuty", 2,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

		ProceduralDistributions.list.LockerValleyMall = {
			rolls = 4,
			items = {
				"Bag_FannyPackFront", 0.8,
				"Bag_Satchel", 0.2,
				"Belt2", 2,
				"Briefcase", 0.2,
				"Disc_Retail", 2,
				"Earbuds", 1,
				"Headphones", 1,
				"HolsterDouble", 0.5,
				"HolsterSimple", 2,
				"Lunchbox", 1,
				"Lunchbox2", 1,
				"Nightstick", 2,
				"Radio.CDplayer", 2,
				"Radio.WalkieTalkie4", 1,
				"HandTorch", 1,
				"Shoes_Black", 6,
				"Shoes_Brown", 6,
				"Suitcase", 0.2,
				"STR.Hat_Security_Mall_Valley", 3,
				"STR.Jacket_Security_Mall_Valley", 3,
				"STR.Shirt_Security_Mall_Valley", 6,
				"STR.TShirt_Security_Mall_Valley", 6,
				"STR.Trousers_Security_Mall_Valley", 4,
			},
			junk = {
				rolls = 1,
				items = {
				
				}
			}
		}

	end
end
Events.OnPreDistributionMerge.Add(preDistributionMerge);