require "Items/ProceduralDistributions"
-- 80sOffroadTireA
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.80sOffroadTireA");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.80sOffroadTireA");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.80sOffroadTireA");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.4);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.80sOffroadTireA");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.80sOffroadTireA");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.5);
-- 80sPickupRoofrackA
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.80sPickupRoofrackA");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.80sPickupRoofrackA");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.80sPickupRoofrackA");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.2);
-- 80sPickupWindowFrontArmor
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.80sPickupWindowFrontArmor");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.80sPickupWindowFrontArmor");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.80sPickupWindowFrontArmor");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- 80sPickupWindshieldArmor
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.80sPickupWindshieldArmor");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.80sPickupWindshieldArmor");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.80sPickupWindshieldArmor");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);
-- 80sPickupSeatFront2
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.80sPickupSeatFront2");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.80sPickupSeatFront2");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.80sPickupSeatFront2");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.1);