function Adjust(Name, Property, Value)
Item = ScriptManager.instance:getItem(Name)
Item:DoParam(Property.." = "..Value)
end

Adjust("Base.Kettle","Weight","0.5")
Adjust("Base.FullKettle","Weight","2.5")
Adjust("Base.FullKettle","UseDelta","0.2")
Adjust("Base.Sugar","Weight","1")
Adjust("Base.Sugar","Calories","1900")
Adjust("Base.Sugar","ThirstChange","50")
Adjust("Base.Sugar","HungerChange","-10")
Adjust("Base.SugarBrown","Weight","1")
Adjust("Base.SugarBrown","Calories","1900")
Adjust("Base.SugarBrown","ThirstChange","50")
Adjust("Base.SugarBrown","HungerChange","-15")

Adjust("Base.Teabag2","Weight","0.01")
Adjust("Base.Teabag2","HungerChange","-5")
Adjust("Base.Teabag2","FatigueChange","-5")
Adjust("Base.Teabag2","UnhappyChange","20")
Adjust("Base.Teabag2","ThirstChange","10")

Adjust("Base.Coffee2","Weight","0.5")
Adjust("Base.Coffee2","HungerChange","-50")
Adjust("Base.Coffee2","FatigueChange","-300")
Adjust("Base.Coffee2","UnhappyChange","60")
Adjust("Base.Coffee2","ThirstChange","100")

Adjust("Base.CocoaPowder","Weight","0.5")
Adjust("Base.CocoaPowder","HungerChange","-120")
Adjust("Base.CocoaPowder","FatigueChange","-60")
Adjust("Base.CocoaPowder","UnhappyChange","-90")
Adjust("Base.CocoaPowder","ThirstChange","60")

Adjust("Base.Mugfull","FatigueChange","-50")
Adjust("Base.Mugfull","UnhappyChange","-20")
Adjust("Base.Mugfull","StressChange","-30")
Adjust("Base.Mugfull","Weight","0.2")
Adjust("Base.Mugfull","ThirstChange","-20")

Adjust("Base.ColdCuppa","FatigueChange","-30")
Adjust("Base.ColdCuppa","UnhappyChange","10")
Adjust("Base.ColdCuppa","Weight","0.2")
Adjust("Base.ColdCuppa","ThirstChange","-20")

Adjust("Base.HotDrinkTea","FatigueChange","-15")
Adjust("Base.HotDrinkTea","HungerChange","-5")
Adjust("Base.HotDrinkTea","StressChange","-15")
Adjust("Base.HotDrinkTea","ThirstChange","-30")

Adjust("Base.HotDrink","FatigueChange","-15")
Adjust("Base.HotDrink","HungerChange","-5")
Adjust("Base.HotDrink","StressChange","-15")
Adjust("Base.HotDrink","ThirstChange","-30")

Adjust("Base.HotDrinkRed","FatigueChange","-15")
Adjust("Base.HotDrinkRed","HungerChange","-5")
Adjust("Base.HotDrinkRed","StressChange","-15")
Adjust("Base.HotDrinkRed","ThirstChange","-30")

Adjust("Base.HotDrinkWhite","FatigueChange","-15")
Adjust("Base.HotDrinkWhite","HungerChange","-5")
Adjust("Base.HotDrinkWhite","StressChange","-15")
Adjust("Base.HotDrinkWhite","ThirstChange","-30")

Adjust("Base.HotDrinkSpiffo","FatigueChange","-15")
Adjust("Base.HotDrinkSpiffo","HungerChange","-5")
Adjust("Base.HotDrinkSpiffo","StressChange","-20")
Adjust("Base.HotDrinkSpiffo","ThirstChange","-30")

Adjust("Base.PillsVitamins","FatigueChange","-10")
Adjust("Base.PillsVitamins","Weight","0.01")
Adjust("Base.PillsVitamins","UseDelta","0.2")