require "Items/ProceduralDistributions"
-- 49powerWagonTire
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.49powerWagonTire");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.49powerWagonTire");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.49powerWagonTire");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.3);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.49powerWagonTire");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.3);
-- 49powerWagonBullbar1
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.49powerWagonBullbar1");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, "Base.49powerWagonBullbar1");
table.insert(ProceduralDistributions.list["MechanicShelfMisc"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, "Base.49powerWagonBullbar1");
table.insert(ProceduralDistributions.list["MechanicShelfTools"].items, 0.1);
-- 49powerWagonFrontFender
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.49powerWagonFrontFender");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.1);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.49powerWagonFrontFender");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);
-- 49powerWagonRearFender
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.49powerWagonRearFender");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.1);