require "Definitions/MakeUpDefinitions"
function addNewMakeUpDefinition(name, item, category)
	local makeup = {};
	makeup.name = name; -- the name you want it to show
	makeup.category = category; -- the category defined further above
	makeup.item = item; -- the item, including the module
	makeup.makeuptypes = {};
	makeup.makeuptypes[category] = true; -- where it's located?
	makeup.makeuptypes["All"] = true;
	makeup.makeuptypes["Tattoo"] = true; -- required for needle to work
	table.insert(MakeUpDefinitions.makeup, makeup);
end

--face
addNewMakeUpDefinition("Face_Tattoo_Paw", "ElliesTattooParlor.Face_Tattoo_Paw", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_Cross", "ElliesTattooParlor.Face_Tattoo_Cross", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_Drop", "ElliesTattooParlor.Face_Tattoo_Drop", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_Heartbroke", "ElliesTattooParlor.Face_Tattoo_Heartbroke", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_Heartlove", "ElliesTattooParlor.Face_Tattoo_Heartlove", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadBoy1", "ElliesTattooParlor.Face_Tattoo_BadBoy1", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadBoy2", "ElliesTattooParlor.Face_Tattoo_BadBoy2", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadBoy3", "ElliesTattooParlor.Face_Tattoo_BadBoy3", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadBoy4", "ElliesTattooParlor.Face_Tattoo_BadBoy4", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadBoy5", "ElliesTattooParlor.Face_Tattoo_BadBoy5", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadGuy1", "ElliesTattooParlor.Face_Tattoo_BadGuy1", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadGuy2", "ElliesTattooParlor.Face_Tattoo_BadGuy2", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadGuy3", "ElliesTattooParlor.Face_Tattoo_BadGuy3", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadGuy4", "ElliesTattooParlor.Face_Tattoo_BadGuy4", "Face_Tattoo")
addNewMakeUpDefinition("Face_Tattoo_BadGuy5", "ElliesTattooParlor.Face_Tattoo_BadGuy5", "Face_Tattoo")

--upper body
addNewMakeUpDefinition("UpperBody_Tattoo_Heartbird", "ElliesTattooParlor.UpperBody_Tattoo_Heartbird", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Heartlove", "ElliesTattooParlor.UpperBody_Tattoo_Heartlove", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Lucky13", "ElliesTattooParlor.UpperBody_Tattoo_Lucky13", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Steeringwheel", "ElliesTattooParlor.UpperBody_Tattoo_Steeringwheel", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Voorhees", "ElliesTattooParlor.UpperBody_Tattoo_Voorhees", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Womenseahorse", "ElliesTattooParlor.UpperBody_Tattoo_Womenseahorse", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Knifewingskull", "ElliesTattooParlor.UpperBody_Tattoo_Knifewingskull", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Satansstar", "ElliesTattooParlor.UpperBody_Tattoo_Satansstar", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Skullsun", "ElliesTattooParlor.UpperBody_Tattoo_Skullsun", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Threeskulls", "ElliesTattooParlor.UpperBody_Tattoo_Threeskulls", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Kingleon", "ElliesTattooParlor.UpperBody_Tattoo_Kingleon", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Crossjesus", "ElliesTattooParlor.UpperBody_Tattoo_Crossjesus", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Ringjesus", "ElliesTattooParlor.UpperBody_Tattoo_Ringjesus", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Blackwolf", "ElliesTattooParlor.UpperBody_Tattoo_Blackwolf", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Japandragon", "ElliesTattooParlor.UpperBody_Tattoo_Japandragon", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Goat", "ElliesTattooParlor.UpperBody_Tattoo_Goat", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Knifeblood", "ElliesTattooParlor.UpperBody_Tattoo_Knifeblood", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Skullfire", "ElliesTattooParlor.UpperBody_Tattoo_Skullfire", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Knifesskull", "ElliesTattooParlor.UpperBody_Tattoo_Knifesskull", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Japanmaskknife", "ElliesTattooParlor.UpperBody_Tattoo_Japanmaskknife", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Skulltattoo", "ElliesTattooParlor.UpperBody_Tattoo_Skulltattoo", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Demonskull", "ElliesTattooParlor.UpperBody_Tattoo_Demonskull", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Skullrose", "ElliesTattooParlor.UpperBody_Tattoo_Skullrose", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_Moth", "ElliesTattooParlor.UpperBody_Tattoo_Moth", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_BadGuy1", "ElliesTattooParlor.UpperBody_Tattoo_BadGuy1", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_BadGuy2", "ElliesTattooParlor.UpperBody_Tattoo_BadGuy2", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_BadGuy3", "ElliesTattooParlor.UpperBody_Tattoo_BadGuy3", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_daggerrabbit", "ElliesTattooParlor.UpperBody_Tattoo_daggerrabbit", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_flowerbud", "ElliesTattooParlor.UpperBody_Tattoo_flowerbud", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_flowercross", "ElliesTattooParlor.UpperBody_Tattoo_flowercross", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_FlowerPower", "ElliesTattooParlor.UpperBody_Tattoo_FlowerPower", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_huntingrabbit", "ElliesTattooParlor.UpperBody_Tattoo_huntingrabbit", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_japaneserabbitmask", "ElliesTattooParlor.UpperBody_Tattoo_japaneserabbitmask", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_rabbitskeleton", "ElliesTattooParlor.UpperBody_Tattoo_rabbitskeleton", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_terribleeaster", "ElliesTattooParlor.UpperBody_Tattoo_terribleeaster", "UpperBody_Tattoo")
addNewMakeUpDefinition("UpperBody_Tattoo_twopartshare", "ElliesTattooParlor.UpperBody_Tattoo_twopartshare", "UpperBody_Tattoo")

--lowerbody
addNewMakeUpDefinition("LowerBody_Tattoo_Eaglefire", "ElliesTattooParlor.LowerBody_Tattoo_Eaglefire", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_KissWomen", "ElliesTattooParlor.LowerBody_Tattoo_KissWomen", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Lucky", "ElliesTattooParlor.LowerBody_Tattoo_Lucky", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Mailheart", "ElliesTattooParlor.LowerBody_Tattoo_Mailheart", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Mermaid", "ElliesTattooParlor.LowerBody_Tattoo_Mermaid", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Naruto", "ElliesTattooParlor.LowerBody_Tattoo_Naruto", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Skullfire", "ElliesTattooParlor.LowerBody_Tattoo_Skullfire", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Blackraven", "ElliesTattooParlor.LowerBody_Tattoo_Blackraven", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Bombpoker", "ElliesTattooParlor.LowerBody_Tattoo_Bombpoker", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Brokenchain", "ElliesTattooParlor.LowerBody_Tattoo_Brokenchain", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Cobraclassic", "ElliesTattooParlor.LowerBody_Tattoo_Cobraclassic", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Crown", "ElliesTattooParlor.LowerBody_Tattoo_Crown", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Demonskullwing", "ElliesTattooParlor.LowerBody_Tattoo_Demonskullwing", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_DragonChina", "ElliesTattooParlor.LowerBody_Tattoo_DragonChina", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Firefighter1982", "ElliesTattooParlor.LowerBody_Tattoo_Firefighter1982", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Griffindragon", "ElliesTattooParlor.LowerBody_Tattoo_Griffindragon", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Hawkfeathers", "ElliesTattooParlor.LowerBody_Tattoo_Hawkfeathers", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Hawksnaikfight", "ElliesTattooParlor.LowerBody_Tattoo_Hawksnaikfight", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Hawkwings", "ElliesTattooParlor.LowerBody_Tattoo_Hawkwings", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_JapanDemon", "ElliesTattooParlor.LowerBody_Tattoo_JapanDemon", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Owl", "ElliesTattooParlor.LowerBody_Tattoo_Owl", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Ringnavelfin", "ElliesTattooParlor.LowerBody_Tattoo_Ringnavelfin", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Ringnavelfish", "ElliesTattooParlor.LowerBody_Tattoo_Ringnavelfish", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Ringnavelsun", "ElliesTattooParlor.LowerBody_Tattoo_Ringnavelsun", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_RoseGreen", "ElliesTattooParlor.LowerBody_Tattoo_RoseGreen", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_ShaikBlack", "ElliesTattooParlor.LowerBody_Tattoo_ShaikBlack", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Sharkatack", "ElliesTattooParlor.LowerBody_Tattoo_Sharkatack", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Sharksun", "ElliesTattooParlor.LowerBody_Tattoo_Sharksun", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Skullpoker", "ElliesTattooParlor.LowerBody_Tattoo_Skullpoker", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Skullroses", "ElliesTattooParlor.LowerBody_Tattoo_Skullroses", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Splintertrashboy", "ElliesTattooParlor.LowerBody_Tattoo_Splintertrashboy", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Stayyoung", "ElliesTattooParlor.LowerBody_Tattoo_Stayyoung", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Thuglife", "ElliesTattooParlor.LowerBody_Tattoo_Thuglife", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_Womenskull", "ElliesTattooParlor.LowerBody_Tattoo_Womenskull", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_ferngirl", "ElliesTattooParlor.LowerBody_Tattoo_ferngirl", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_hummingbirdskeleton", "ElliesTattooParlor.LowerBody_Tattoo_hummingbirdskeleton", "LowerBody_Tattoo")
addNewMakeUpDefinition("LowerBody_Tattoo_moonhares", "ElliesTattooParlor.LowerBody_Tattoo_moonhares", "LowerBody_Tattoo")

--leftarm
addNewMakeUpDefinition("LeftArm_Tattoo_Birdflag", "ElliesTattooParlor.LeftArm_Tattoo_Birdflag", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Birds", "ElliesTattooParlor.LeftArm_Tattoo_Birds", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Jamaica", "ElliesTattooParlor.LeftArm_Tattoo_Jamaica", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Kniferose", "ElliesTattooParlor.LeftArm_Tattoo_Kniferose", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_KnifeSkull", "ElliesTattooParlor.LeftArm_Tattoo_KnifeSkull", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Lighthouse", "ElliesTattooParlor.LeftArm_Tattoo_Lighthouse", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Phoenix", "ElliesTattooParlor.LeftArm_Tattoo_Phoenix", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SexWomen", "ElliesTattooParlor.LeftArm_Tattoo_SexWomen", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Dragoninfinity", "ElliesTattooParlor.LeftArm_Tattoo_Dragoninfinity", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Fishcarp", "ElliesTattooParlor.LeftArm_Tattoo_Fishcarp", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Fishcarp2", "ElliesTattooParlor.LeftArm_Tattoo_Fishcarp2", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_FishKnuckle", "ElliesTattooParlor.LeftArm_Tattoo_FishKnuckle", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Heartdagger", "ElliesTattooParlor.LeftArm_Tattoo_Heartdagger", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Japandragomblack", "ElliesTattooParlor.LeftArm_Tattoo_Japandragomblack", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Japandragonwhite", "ElliesTattooParlor.LeftArm_Tattoo_Japandragonwhite", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevecarpblack", "ElliesTattooParlor.LeftArm_Tattoo_Sleevecarpblack", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevefiredragon", "ElliesTattooParlor.LeftArm_Tattoo_Sleevefiredragon", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevehalloween", "ElliesTattooParlor.LeftArm_Tattoo_Sleevehalloween", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool1", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool1", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool2", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool2", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool3", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool3", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool4", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool4", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool5", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool5", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool6", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool6", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SleeveOldschool7", "ElliesTattooParlor.LeftArm_Tattoo_SleeveOldschool7", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevepeacock", "ElliesTattooParlor.LeftArm_Tattoo_Sleevepeacock", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleeveskulls", "ElliesTattooParlor.LeftArm_Tattoo_Sleeveskulls", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevestripes", "ElliesTattooParlor.LeftArm_Tattoo_Sleevestripes", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Sleevetigerwomens", "ElliesTattooParlor.LeftArm_Tattoo_Sleevetigerwomens", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_SnaikBlack", "ElliesTattooParlor.LeftArm_Tattoo_SnaikBlack", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_Snaiktrident", "ElliesTattooParlor.LeftArm_Tattoo_Snaiktrident", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_huntingrabbit", "ElliesTattooParlor.LeftArm_Tattoo_huntingrabbit", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_sakura", "ElliesTattooParlor.LeftArm_Tattoo_sakura", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_sweeteaster1", "ElliesTattooParlor.LeftArm_Tattoo_sweeteaster1", "LeftArm_Tattoo")
addNewMakeUpDefinition("LeftArm_Tattoo_sweeteaster2", "ElliesTattooParlor.LeftArm_Tattoo_sweeteaster2", "LeftArm_Tattoo")

--rightarm
addNewMakeUpDefinition("RightArm_Tattoo_Anchor", "ElliesTattooParlor.RightArm_Tattoo_Anchor", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Eagle", "ElliesTattooParlor.RightArm_Tattoo_Eagle", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Skullsnake", "ElliesTattooParlor.RightArm_Tattoo_Skullsnake", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Women", "ElliesTattooParlor.RightArm_Tattoo_Women", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Dragoninfinity", "ElliesTattooParlor.RightArm_Tattoo_Dragoninfinity", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Fishcarp", "ElliesTattooParlor.RightArm_Tattoo_Fishcarp", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Fishcarp2", "ElliesTattooParlor.RightArm_Tattoo_Fishcarp2", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_FishKnuckle", "ElliesTattooParlor.RightArm_Tattoo_FishKnuckle", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Heartdagger", "ElliesTattooParlor.RightArm_Tattoo_Heartdagger", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Japandragomblack", "ElliesTattooParlor.RightArm_Tattoo_Japandragomblack", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Japandragonwhite", "ElliesTattooParlor.RightArm_Tattoo_Japandragonwhite", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevecarpblack", "ElliesTattooParlor.RightArm_Tattoo_Sleevecarpblack", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevefiredragon", "ElliesTattooParlor.RightArm_Tattoo_Sleevefiredragon", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevehalloween", "ElliesTattooParlor.RightArm_Tattoo_Sleevehalloween", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool1", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool1", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool2", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool2", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool3", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool3", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool4", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool4", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool5", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool5", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool6", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool6", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SleeveOldschool7", "ElliesTattooParlor.RightArm_Tattoo_SleeveOldschool7", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevepeacock", "ElliesTattooParlor.RightArm_Tattoo_Sleevepeacock", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleeveskulls", "ElliesTattooParlor.RightArm_Tattoo_Sleeveskulls", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevestripes", "ElliesTattooParlor.RightArm_Tattoo_Sleevestripes", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Sleevetigerwomens", "ElliesTattooParlor.RightArm_Tattoo_Sleevetigerwomens", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_SnaikBlack", "ElliesTattooParlor.RightArm_Tattoo_SnaikBlack", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_Snaiktrident", "ElliesTattooParlor.RightArm_Tattoo_Snaiktrident", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_huntingrabbit", "ElliesTattooParlor.RightArm_Tattoo_huntingrabbit", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_sakura", "ElliesTattooParlor.RightArm_Tattoo_sakura", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_sweeteaster1", "ElliesTattooParlor.RightArm_Tattoo_sweeteaster1", "RightArm_Tattoo")
addNewMakeUpDefinition("RightArm_Tattoo_sweeteaster2", "ElliesTattooParlor.RightArm_Tattoo_sweeteaster2", "RightArm_Tattoo")

--leftleg
addNewMakeUpDefinition("LeftLeg_Tattoo_Anchormen", "ElliesTattooParlor.LeftLeg_Tattoo_Anchormen", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Cherry", "ElliesTattooParlor.LeftLeg_Tattoo_Cherry", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_RoseYellow", "ElliesTattooParlor.LeftLeg_Tattoo_RoseYellow", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Snake", "ElliesTattooParlor.LeftLeg_Tattoo_Snake", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Eagleskull", "ElliesTattooParlor.LeftLeg_Tattoo_Eagleskull", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Japancatmask", "ElliesTattooParlor.LeftLeg_Tattoo_Japancatmask", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Japandragon", "ElliesTattooParlor.LeftLeg_Tattoo_Japandragon", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Japanmask1", "ElliesTattooParlor.LeftLeg_Tattoo_Japanmask1", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Japanmask2", "ElliesTattooParlor.LeftLeg_Tattoo_Japanmask2", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Palmtrees", "ElliesTattooParlor.LeftLeg_Tattoo_Palmtrees", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Pineapple", "ElliesTattooParlor.LeftLeg_Tattoo_Pineapple", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Screamcat", "ElliesTattooParlor.LeftLeg_Tattoo_Screamcat", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Skullsnaik", "ElliesTattooParlor.LeftLeg_Tattoo_Skullsnaik", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Sleeveline1", "ElliesTattooParlor.LeftLeg_Tattoo_Sleeveline1", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Sleeveline2", "ElliesTattooParlor.LeftLeg_Tattoo_Sleeveline2", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Sleeveline3", "ElliesTattooParlor.LeftLeg_Tattoo_Sleeveline3", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Sleevelinefire1", "ElliesTattooParlor.LeftLeg_Tattoo_Sleevelinefire1", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Sleevelinefire2", "ElliesTattooParlor.LeftLeg_Tattoo_Sleevelinefire2", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_SleeveOldschool1", "ElliesTattooParlor.LeftLeg_Tattoo_SleeveOldschool1", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_SleeveOldschool2", "ElliesTattooParlor.LeftLeg_Tattoo_SleeveOldschool2", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_SleeveOldschool3", "ElliesTattooParlor.LeftLeg_Tattoo_SleeveOldschool3", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_SleeveOldschool4", "ElliesTattooParlor.LeftLeg_Tattoo_SleeveOldschool4", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_SleeveOldschool5", "ElliesTattooParlor.LeftLeg_Tattoo_SleeveOldschool5", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Snaikblood", "ElliesTattooParlor.LeftLeg_Tattoo_Snaikblood", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Snaikflawer", "ElliesTattooParlor.LeftLeg_Tattoo_Snaikflawer", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Snaikinskull", "ElliesTattooParlor.LeftLeg_Tattoo_Snaikinskull", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Spaiderlove1", "ElliesTattooParlor.LeftLeg_Tattoo_Spaiderlove1", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_Spaiderlove2", "ElliesTattooParlor.LeftLeg_Tattoo_Spaiderlove2", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_dandelionflowers", "ElliesTattooParlor.LeftLeg_Tattoo_dandelionflowers", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_hares", "ElliesTattooParlor.LeftLeg_Tattoo_hares", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_huntingrabbit", "ElliesTattooParlor.LeftLeg_Tattoo_huntingrabbit", "LeftLeg_Tattoo")
addNewMakeUpDefinition("LeftLeg_Tattoo_smokinggirl", "ElliesTattooParlor.LeftLeg_Tattoo_smokinggirl", "LeftLeg_Tattoo")

--rightleg
addNewMakeUpDefinition("RightLeg_Tattoo_Anchorheart", "ElliesTattooParlor.RightLeg_Tattoo_Anchorheart", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Ship", "ElliesTattooParlor.RightLeg_Tattoo_Ship", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Skullrose", "ElliesTattooParlor.RightLeg_Tattoo_Skullrose", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Eagleskull", "ElliesTattooParlor.RightLeg_Tattoo_Eagleskull", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Japancatmask", "ElliesTattooParlor.RightLeg_Tattoo_Japancatmask", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Japandragon", "ElliesTattooParlor.RightLeg_Tattoo_Japandragon", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Japanmask1", "ElliesTattooParlor.RightLeg_Tattoo_Japanmask1", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Japanmask2", "ElliesTattooParlor.RightLeg_Tattoo_Japanmask2", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Palmtrees", "ElliesTattooParlor.RightLeg_Tattoo_Palmtrees", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Pineapple", "ElliesTattooParlor.RightLeg_Tattoo_Pineapple", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Screamcat", "ElliesTattooParlor.RightLeg_Tattoo_Screamcat", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Skullsnaik", "ElliesTattooParlor.RightLeg_Tattoo_Skullsnaik", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Sleeveline1", "ElliesTattooParlor.RightLeg_Tattoo_Sleeveline1", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Sleeveline2", "ElliesTattooParlor.RightLeg_Tattoo_Sleeveline2", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Sleeveline3", "ElliesTattooParlor.RightLeg_Tattoo_Sleeveline3", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Sleevelinefire1", "ElliesTattooParlor.RightLeg_Tattoo_Sleevelinefire1", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Sleevelinefire2", "ElliesTattooParlor.RightLeg_Tattoo_Sleevelinefire2", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_SleeveOldschool1", "ElliesTattooParlor.RightLeg_Tattoo_SleeveOldschool1", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_SleeveOldschool2", "ElliesTattooParlor.RightLeg_Tattoo_SleeveOldschool2", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_SleeveOldschool3", "ElliesTattooParlor.RightLeg_Tattoo_SleeveOldschool3", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_SleeveOldschool4", "ElliesTattooParlor.RightLeg_Tattoo_SleeveOldschool4", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_SleeveOldschool5", "ElliesTattooParlor.RightLeg_Tattoo_SleeveOldschool5", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Snaikblood", "ElliesTattooParlor.RightLeg_Tattoo_Snaikblood", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Snaikflawer", "ElliesTattooParlor.RightLeg_Tattoo_Snaikflawer", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Snaikinskull", "ElliesTattooParlor.RightLeg_Tattoo_Snaikinskull", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Spaiderlove1", "ElliesTattooParlor.RightLeg_Tattoo_Spaiderlove1", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_Spaiderlove2", "ElliesTattooParlor.RightLeg_Tattoo_Spaiderlove2", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_dandelionflowers", "ElliesTattooParlor.RightLeg_Tattoo_dandelionflowers", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_hares", "ElliesTattooParlor.RightLeg_Tattoo_hares", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_huntingrabbit", "ElliesTattooParlor.RightLeg_Tattoo_huntingrabbit", "RightLeg_Tattoo")
addNewMakeUpDefinition("RightLeg_Tattoo_smokinggirl", "ElliesTattooParlor.RightLeg_Tattoo_smokinggirl", "RightLeg_Tattoo")

--back 
addNewMakeUpDefinition("Back_Tattoo_Panther", "ElliesTattooParlor.Back_Tattoo_Panther", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Skull", "ElliesTattooParlor.Back_Tattoo_Skull", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Wings", "ElliesTattooParlor.Back_Tattoo_Wings", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Womenskull", "ElliesTattooParlor.Back_Tattoo_Womenskull", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Amurtiger", "ElliesTattooParlor.Back_Tattoo_Amurtiger", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Devilbiker", "ElliesTattooParlor.Back_Tattoo_Devilbiker", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Devilskull", "ElliesTattooParlor.Back_Tattoo_Devilskull", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Engine", "ElliesTattooParlor.Back_Tattoo_Engine", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Hornedskull", "ElliesTattooParlor.Back_Tattoo_Hornedskull", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Japanesecarp", "ElliesTattooParlor.Back_Tattoo_Japanesecarp", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Japanesedemon", "ElliesTattooParlor.Back_Tattoo_Japanesedemon", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Japanesedemonmasks", "ElliesTattooParlor.Back_Tattoo_Japanesedemonmasks", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Jesuschrist", "ElliesTattooParlor.Back_Tattoo_Jesuschrist", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Originalbiker", "ElliesTattooParlor.Back_Tattoo_Originalbiker", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Paletobay", "ElliesTattooParlor.Back_Tattoo_Paletobay", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Samurai", "ElliesTattooParlor.Back_Tattoo_Samurai", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Sexwomennaked", "ElliesTattooParlor.Back_Tattoo_Sexwomennaked", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_Skullfirewings", "ElliesTattooParlor.Back_Tattoo_Skullfirewings", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_haresgraze", "ElliesTattooParlor.Back_Tattoo_haresgraze", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_rabbitdonut1", "ElliesTattooParlor.Back_Tattoo_rabbitdonut1", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_rabbitdonut2", "ElliesTattooParlor.Back_Tattoo_rabbitdonut2", "Back_Tattoo")
addNewMakeUpDefinition("Back_Tattoo_twopartshare", "ElliesTattooParlor.Back_Tattoo_twopartshare", "Back_Tattoo")
