require 'Items/ProceduralDistributions'
require 'Items/SuburbsDistributions'

table.insert(SuburbsDistributions["Paperbag_Spiffos"].items, "SpiffoCards.cardpack");
table.insert(SuburbsDistributions["Paperbag_Spiffos"].items, 90);
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, 80);
table.insert(ProceduralDistributions.list["SpiffosKitchenCounter"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["SpiffosKitchenCounter"].items, 20);
table.insert(ProceduralDistributions.list["SpiffosDiningCounter"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["SpiffosDiningCounter"].items, 15);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 15);
table.insert(ProceduralDistributions.list["CrateToys"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["CrateToys"].items, 5);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 5);
table.insert(ProceduralDistributions.list["SchoolLockers"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["SchoolLockers"].items, 3);
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["ClassroomDesk"].items, 3);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 2);
table.insert(ProceduralDistributions.list["Hobbies"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["Hobbies"].items, 2);
table.insert(ProceduralDistributions.list["HolidayStuff"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["HolidayStuff"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["LivingRoomShelfNoTapes"].items, 1);
table.insert(ProceduralDistributions.list["RandomFiller"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["RandomFiller"].items, 0.5);
table.insert(SuburbsDistributions.all.inventorymale.items, "SpiffoCards.cardpack")
table.insert(SuburbsDistributions.all.inventorymale.items, 2)
table.insert(SuburbsDistributions.all.inventoryfemale.items, "SpiffoCards.cardpack")
table.insert(SuburbsDistributions.all.inventoryfemale.items, 2)
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, "SpiffoCards.cardpackgold");
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, 40);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "SpiffoCards.cardpackgold");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 10);
table.insert(ProceduralDistributions.list["SpiffosDiningCounter"].items, "SpiffoCards.cardpack");
table.insert(ProceduralDistributions.list["SpiffosDiningCounter"].items, 5);
table.insert(ProceduralDistributions.list["WardrobeChild"].items, "SpiffoCards.cardpackgold");
table.insert(ProceduralDistributions.list["WardrobeChild"].items, 1);