-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["d_furniture_bedroom_01_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_01_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_02_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_02_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_03_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_03_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_04_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_04_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["d_furniture_bedroom_05_48"] = {{ name = "other", tiles = {"books&misc_01_60", "books&misc_01_62"} }, { name = "other", tiles = {"books&misc_02_60", "books&misc_02_62"} }}
overlayMap["d_furniture_bedroom_05_49"] = {{ name = "other", tiles = {"books&misc_01_61", "books&misc_01_63"} }, { name = "other", tiles = {"books&misc_02_61", "books&misc_02_63"} }}
overlayMap["furniture_storage_ddd_01_0"] = {{ name = "other", tiles = {"container_overlays_ddd_01_8", "container_overlays_ddd_01_0"} }}
overlayMap["furniture_storage_ddd_01_1"] = {{ name = "other", tiles = {"container_overlays_ddd_01_9", "container_overlays_ddd_01_1"} }}
overlayMap["furniture_storage_ddd_01_2"] = {{ name = "other", tiles = {"container_overlays_ddd_01_10", "container_overlays_ddd_01_2"} }}
overlayMap["furniture_storage_ddd_01_3"] = {{ name = "other", tiles = {"container_overlays_ddd_01_11", "container_overlays_ddd_01_3"} }}
overlayMap["furniture_storage_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_40", "container_overlays_ddd_01_32"} }}
overlayMap["furniture_storage_ddd_01_14"] = {{ name = "other", tiles = {"books&misc_01_24", "books&misc_01_28"} }}
overlayMap["furniture_storage_ddd_01_15"] = {{ name = "other", tiles = {"books&misc_01_27", "books&misc_01_31"} }}
overlayMap["furniture_storage_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_24", "container_overlays_ddd_01_16"} }}
overlayMap["furniture_storage_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_25", "container_overlays_ddd_01_17"} }}
overlayMap["furniture_storage_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_26", "container_overlays_ddd_01_18"} }}
overlayMap["furniture_storage_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_27", "container_overlays_ddd_01_19"} }}
overlayMap["furniture_storage_ddd_01_32"] = {{ name = "other", tiles = {"container_overlays_ddd_01_42", "container_overlays_ddd_01_34"} }}
overlayMap["furniture_storage_ddd_01_33"] = {{ name = "other", tiles = {"container_overlays_ddd_01_43", "container_overlays_ddd_01_35"} }}
overlayMap["furniture_storage_ddd_01_34"] = {{ name = "other", tiles = {"container_overlays_ddd_01_42", "container_overlays_ddd_01_34"} }}
overlayMap["furniture_storage_ddd_01_35"] = {{ name = "other", tiles = {"container_overlays_ddd_01_43", "container_overlays_ddd_01_35"} }}
overlayMap["furniture_storage_ddd_01_48"] = {{ name = "other", tiles = {"container_overlays_ddd_01_60", "container_overlays_ddd_01_60"} }}
overlayMap["furniture_storage_ddd_01_51"] = {{ name = "other", tiles = {"container_overlays_ddd_01_59", "container_overlays_ddd_01_59"} }}
overlayMap["furniture_storage_ddd_01_53"] = {{ name = "other", tiles = {"container_overlays_ddd_01_61", "container_overlays_ddd_01_61"} }}
overlayMap["furniture_storage_ddd_01_54"] = {{ name = "other", tiles = {"container_overlays_ddd_01_62", "container_overlays_ddd_01_62"} }}
overlayMap["furniture_storage_ddd_01_55"] = {{ name = "other", tiles = {"container_overlays_ddd_01_63", "container_overlays_ddd_01_63"} }}
overlayMap["industry_dirkea_ddd_01_12"] = {{ name = "other", tiles = {"container_overlays_ddd_01_12", "container_overlays_ddd_01_4"} }}
overlayMap["industry_dirkea_ddd_01_13"] = {{ name = "other", tiles = {"container_overlays_ddd_01_13", "container_overlays_ddd_01_5"} }}
overlayMap["industry_dirkea_ddd_01_14"] = {{ name = "other", tiles = {"container_overlays_ddd_01_6", "container_overlays_ddd_01_14"} }}
overlayMap["industry_dirkea_ddd_01_15"] = {{ name = "other", tiles = {"container_overlays_ddd_01_7", "container_overlays_ddd_01_15"} }}
overlayMap["industry_dirkea_ddd_01_24"] = {{ name = "other", tiles = {"container_overlays_ddd_01_20", "container_overlays_ddd_01_20"} }, { name = "other", tiles = {"container_overlays_ddd_01_28", "container_overlays_ddd_01_28"} }}
overlayMap["industry_dirkea_ddd_01_25"] = {{ name = "other", tiles = {"container_overlays_ddd_01_21", "container_overlays_ddd_01_21"} }, { name = "other", tiles = {"container_overlays_ddd_01_29", "container_overlays_ddd_01_29"} }}
overlayMap["industry_dirkea_ddd_01_26"] = {{ name = "other", tiles = {"container_overlays_ddd_01_22", "container_overlays_ddd_01_22"} }, { name = "other", tiles = {"container_overlays_ddd_01_30", "container_overlays_ddd_01_30"} }}
overlayMap["industry_dirkea_ddd_01_27"] = {{ name = "other", tiles = {"container_overlays_ddd_01_23", "container_overlays_ddd_01_23"} }, { name = "other", tiles = {"container_overlays_ddd_01_31", "container_overlays_ddd_01_31"} }}
overlayMap["industry_dirkea_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_36", "container_overlays_ddd_01_44"} }, { name = "other", tiles = {"container_overlays_ddd_01_37", "container_overlays_ddd_01_45"} }}
overlayMap["industry_dirkea_ddd_01_38"] = {{ name = "other", tiles = {"container_overlays_ddd_01_38", "container_overlays_ddd_01_46"} }, { name = "other", tiles = {"container_overlays_ddd_01_39", "container_overlays_ddd_01_47"} }}
overlayMap["industry_railroad_ddd_01_28"] = {{ name = "other", tiles = {"container_overlays_ddd_01_54", "container_overlays_ddd_01_54"} }}
overlayMap["industry_railroad_ddd_01_29"] = {{ name = "other", tiles = {"container_overlays_ddd_01_55", "container_overlays_ddd_01_55"} }}
overlayMap["industry_railroad_ddd_01_36"] = {{ name = "other", tiles = {"container_overlays_ddd_01_52", "container_overlays_ddd_01_52"} }}
overlayMap["industry_railroad_ddd_01_37"] = {{ name = "other", tiles = {"container_overlays_ddd_01_53", "container_overlays_ddd_01_53"} }}
overlayMap["location_shop_generic_ddd_01_2"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_3"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_4"] = {{ name = "other", tiles = {"container_overlays_ddd_01_20", "container_overlays_ddd_01_20"} }, { name = "other", tiles = {"container_overlays_ddd_01_28", "container_overlays_ddd_01_28"} }}
overlayMap["location_shop_generic_ddd_01_5"] = {{ name = "other", tiles = {"container_overlays_ddd_01_21", "container_overlays_ddd_01_21"} }, { name = "other", tiles = {"container_overlays_ddd_01_29", "container_overlays_ddd_01_29"} }}
overlayMap["location_shop_generic_ddd_01_6"] = {{ name = "other", tiles = {"container_overlays_ddd_01_22", "container_overlays_ddd_01_22"} }, { name = "other", tiles = {"container_overlays_ddd_01_30", "container_overlays_ddd_01_30"} }}
overlayMap["location_shop_generic_ddd_01_7"] = {{ name = "other", tiles = {"container_overlays_ddd_01_23", "container_overlays_ddd_01_23"} }, { name = "other", tiles = {"container_overlays_ddd_01_31", "container_overlays_ddd_01_31"} }}
overlayMap["location_shop_generic_ddd_01_8"] = {{ name = "other", tiles = {"books&misc_02_72", "books&misc_02_80"} }, { name = "other", tiles = {"books&misc_01_72", "books&misc_01_80"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }, { name = "other", tiles = {"food_01_8", "food_01_16"} }}
overlayMap["location_shop_generic_ddd_01_9"] = {{ name = "other", tiles = {"books&misc_02_73", "books&misc_02_81"} }, { name = "other", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "other", tiles = {"food_01_9", "food_01_17"} }}
overlayMap["location_shop_generic_ddd_01_10"] = {{ name = "other", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "other", tiles = {"books&misc_02_73", "books&misc_02_81"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "other", tiles = {"food_01_9", "food_01_17"} }}
overlayMap["location_shop_generic_ddd_01_11"] = {{ name = "other", tiles = {"books&misc_01_74", "books&misc_01_82"} }, { name = "other", tiles = {"books&misc_02_74", "books&misc_02_82"} }, { name = "other", tiles = {"food_02_10", "food_02_18"} }, { name = "other", tiles = {"food_01_10", "food_01_18"} }}
overlayMap["location_shop_generic_ddd_01_12"] = {{ name = "other", tiles = {"books&misc_02_75", "books&misc_02_83"} }, { name = "other", tiles = {"books&misc_01_75", "books&misc_01_83"} }, { name = "other", tiles = {"food_02_11", "food_02_19"} }, { name = "other", tiles = {"food_01_11", "food_01_19"} }}
overlayMap["location_shop_generic_ddd_01_13"] = {{ name = "other", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "other", tiles = {"books&misc_02_76", "books&misc_02_84"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "other", tiles = {"food_01_12", "food_01_20"} }}
overlayMap["location_shop_generic_ddd_01_14"] = {{ name = "other", tiles = {"books&misc_02_76", "books&misc_02_84"} }, { name = "other", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "other", tiles = {"food_01_12", "food_01_20"} }}
overlayMap["location_shop_generic_ddd_01_15"] = {{ name = "other", tiles = {"books&misc_02_77", "books&misc_02_85"} }, { name = "other", tiles = {"books&misc_01_77", "books&misc_01_85"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }, { name = "other", tiles = {"food_01_13", "food_01_21"} }}
overlayMap["location_shop_generic_ddd_01_24"] = {{ name = "other", tiles = {"books&misc_01_12", "books&misc_01_20"} }, { name = "other", tiles = {"books&misc_02_12", "books&misc_02_20"} }}
overlayMap["location_shop_generic_ddd_01_25"] = {{ name = "other", tiles = {"books&misc_01_13", "books&misc_01_21"} }, { name = "other", tiles = {"books&misc_02_13", "books&misc_02_21"} }}
overlayMap["location_shop_generic_ddd_01_26"] = {{ name = "other", tiles = {"books&misc_01_14", "books&misc_01_22"} }, { name = "other", tiles = {"books&misc_02_14", "books&misc_02_22"} }}
overlayMap["location_shop_generic_ddd_01_27"] = {{ name = "other", tiles = {"books&misc_01_15", "books&misc_01_23"} }, { name = "other", tiles = {"books&misc_02_15", "books&misc_02_23"} }}
overlayMap["location_shop_generic_ddd_01_28"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_29"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_30"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_31"] = {{ name = "other", tiles = {"none"} }}
overlayMap["location_shop_generic_ddd_01_32"] = {{ name = "other", tiles = {"food_02_24", "food_02_28"} }}
overlayMap["location_shop_generic_ddd_01_33"] = {{ name = "other", tiles = {"food_02_25", "food_02_29"} }}
overlayMap["location_shop_generic_ddd_01_34"] = {{ name = "other", tiles = {"food_02_26", "food_02_30"} }}
overlayMap["location_shop_generic_ddd_01_35"] = {{ name = "other", tiles = {"food_02_27", "food_02_31"} }}
overlayMap["location_shop_generic_ddd_01_36"] = {{ name = "other", tiles = {"clothing_02_14", "clothing_02_22"} }, { name = "other", tiles = {"clothing_01_14", "clothing_01_22"} }}
overlayMap["location_shop_generic_ddd_01_37"] = {{ name = "other", tiles = {"clothing_01_15", "clothing_01_23"} }, { name = "other", tiles = {"clothing_02_15", "clothing_02_23"} }}
overlayMap["location_shop_generic_ddd_01_38"] = {{ name = "other", tiles = {"clothing_01_48", "clothing_01_50"} }, { name = "other", tiles = {"clothing_02_48", "clothing_02_50"} }}
overlayMap["location_shop_generic_ddd_01_39"] = {{ name = "other", tiles = {"clothing_02_49", "clothing_02_51"} }, { name = "other", tiles = {"clothing_01_49", "clothing_01_51"} }}
overlayMap["location_shop_generic_ddd_01_40"] = {{ name = "other", tiles = {"clothing_01_8", "clothing_01_16"} }, { name = "other", tiles = {"clothing_02_8", "clothing_02_16"} }}
overlayMap["location_shop_generic_ddd_01_41"] = {{ name = "other", tiles = {"clothing_01_9", "clothing_01_17"} }, { name = "other", tiles = {"clothing_02_9", "clothing_02_17"} }}
overlayMap["location_shop_generic_ddd_01_42"] = {{ name = "other", tiles = {"clothing_01_10", "clothing_01_18"} }, { name = "other", tiles = {"clothing_02_10", "clothing_02_18"} }}
overlayMap["location_shop_generic_ddd_01_45"] = {{ name = "other", tiles = {"clothing_01_11", "clothing_01_19"} }, { name = "other", tiles = {"clothing_02_11", "clothing_02_19"} }}
overlayMap["location_shop_generic_ddd_01_46"] = {{ name = "other", tiles = {"clothing_01_12", "clothing_01_20"} }, { name = "other", tiles = {"clothing_02_12", "clothing_02_20"} }}
overlayMap["location_shop_generic_ddd_01_47"] = {{ name = "other", tiles = {"clothing_01_13", "clothing_01_21"} }, { name = "other", tiles = {"clothing_02_13", "clothing_02_21"} }}
overlayMap["location_shop_generic_ddd_01_56"] = {{ name = "other", tiles = {"books&misc_02_64", "books&misc_02_68"} }, { name = "other", tiles = {"books&misc_01_64", "books&misc_01_68"} }}
overlayMap["location_shop_generic_ddd_01_57"] = {{ name = "other", tiles = {"books&misc_02_65", "books&misc_02_69"} }, { name = "other", tiles = {"books&misc_01_65", "books&misc_01_69"} }}
overlayMap["location_shop_generic_ddd_01_58"] = {{ name = "other", tiles = {"books&misc_02_66", "books&misc_02_70"} }, { name = "other", tiles = {"books&misc_01_66", "books&misc_01_70"} }}
overlayMap["location_shop_generic_ddd_01_59"] = {{ name = "other", tiles = {"books&misc_02_67", "books&misc_02_71"} }, { name = "other", tiles = {"books&misc_01_67", "books&misc_01_71"} }}
overlayMap["location_shop_generic_ddd_01_64"] = {{ name = "other", tiles = {"food_01_32", "food_01_36"} }, { name = "other", tiles = {"food_02_32", "food_02_36"} }}
overlayMap["location_shop_generic_ddd_01_65"] = {{ name = "other", tiles = {"food_01_33", "food_01_37"} }, { name = "other", tiles = {"food_02_33", "food_02_37"} }}
overlayMap["location_shop_generic_ddd_01_66"] = {{ name = "other", tiles = {"food_01_34", "food_01_38"} }, { name = "other", tiles = {"food_02_34", "food_02_38"} }}
overlayMap["location_shop_generic_ddd_01_67"] = {{ name = "other", tiles = {"food_01_35", "food_01_39"} }, { name = "other", tiles = {"food_02_35", "food_02_39"} }}
overlayMap["location_shop_generic_ddd_01_68"] = {{ name = "other", tiles = {"food_01_40", "food_01_44"} }, { name = "other", tiles = {"food_02_40", "food_02_44"} }}
overlayMap["location_shop_generic_ddd_01_69"] = {{ name = "other", tiles = {"food_01_41", "food_01_45"} }, { name = "other", tiles = {"food_02_41", "food_02_45"} }}
overlayMap["location_shop_generic_ddd_01_70"] = {{ name = "other", tiles = {"food_01_42", "food_01_46"} }, { name = "other", tiles = {"food_02_42", "food_02_46"} }}
overlayMap["location_shop_generic_ddd_01_71"] = {{ name = "other", tiles = {"food_01_43", "food_01_47"} }, { name = "other", tiles = {"food_02_43", "food_02_47"} }}
overlayMap["location_shop_generic_ddd_01_80"] = {{ name = "other", tiles = {"books&misc_01_112", "books&misc_01_116"} }}
overlayMap["location_shop_generic_ddd_01_81"] = {{ name = "other", tiles = {"books&misc_01_113", "books&misc_01_117"} }}
overlayMap["location_shop_generic_ddd_01_82"] = {{ name = "other", tiles = {"books&misc_01_114", "books&misc_01_118"} }}
overlayMap["location_shop_generic_ddd_01_83"] = {{ name = "other", tiles = {"books&misc_01_115", "books&misc_01_119"} }}
overlayMap["location_shop_generic_ddd_01_88"] = {{ name = "other", tiles = {"books&misc_01_120", "books&misc_01_124"} }}
overlayMap["location_shop_generic_ddd_01_89"] = {{ name = "other", tiles = {"books&misc_01_121", "books&misc_01_125"} }}
overlayMap["location_shop_generic_ddd_01_90"] = {{ name = "other", tiles = {"books&misc_01_122", "books&misc_01_126"} }}
overlayMap["location_shop_generic_ddd_01_91"] = {{ name = "other", tiles = {"books&misc_01_123", "books&misc_01_127"} }}
overlayMap["location_shop_generic_ddd_01_96"] = {{ name = "other", tiles = {"books&misc_01_88", "books&misc_01_96"} }}
overlayMap["location_shop_generic_ddd_01_97"] = {{ name = "other", tiles = {"books&misc_01_89", "books&misc_01_97"} }}
overlayMap["location_shop_generic_ddd_01_98"] = {{ name = "other", tiles = {"books&misc_01_90", "books&misc_01_98"} }}
overlayMap["location_shop_generic_ddd_01_99"] = {{ name = "other", tiles = {"books&misc_01_91", "books&misc_01_99"} }}
overlayMap["location_shop_generic_ddd_01_100"] = {{ name = "other", tiles = {"books&misc_01_92", "books&misc_01_100"} }}
overlayMap["location_shop_generic_ddd_01_101"] = {{ name = "other", tiles = {"books&misc_01_93", "books&misc_01_101"} }}
overlayMap["location_shop_generic_ddd_01_102"] = {{ name = "other", tiles = {"books&misc_01_94", "books&misc_01_102"} }}
overlayMap["location_shop_generic_ddd_01_103"] = {{ name = "other", tiles = {"books&misc_01_95", "books&misc_01_103"} }}
overlayMap["location_shop_generic_ddd_01_104"] = {{ name = "other", tiles = {"food_02_24", "food_02_28"} }}
overlayMap["location_shop_generic_ddd_01_105"] = {{ name = "other", tiles = {"food_02_25", "food_02_29"} }}
overlayMap["location_shop_generic_ddd_01_106"] = {{ name = "other", tiles = {"food_02_26", "food_02_30"} }}
overlayMap["location_shop_generic_ddd_01_107"] = {{ name = "other", tiles = {"food_02_27", "food_02_31"} }}
overlayMap["location_shop_generic_ddd_01_108"] = {{ name = "other", tiles = {"clothing_02_33", "clothing_02_41"} }}
overlayMap["location_shop_generic_ddd_01_109"] = {{ name = "other", tiles = {"clothing_02_36", "clothing_02_44"} }}
overlayMap["location_shop_generic_ddd_01_112"] = {{ name = "other", tiles = {"food_01_8", "food_01_16"} }, { name = "other", tiles = {"food_02_8", "food_02_16"} }, { name = "other", tiles = {"books&misc_01_72", "books&misc_01_80"} }, { name = "other", tiles = {"books&misc_02_72", "books&misc_02_80"} }}
overlayMap["location_shop_generic_ddd_01_113"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "other", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "other", tiles = {"books&misc_02_73", "books&misc_02_81"} }}
overlayMap["location_shop_generic_ddd_01_114"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }, { name = "other", tiles = {"food_02_9", "food_02_17"} }, { name = "other", tiles = {"books&misc_01_73", "books&misc_01_81"} }, { name = "other", tiles = {"books&misc_02_73", "books&misc_02_81"} }}
overlayMap["location_shop_generic_ddd_01_117"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "other", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "other", tiles = {"books&misc_02_76", "books&misc_02_84"} }}
overlayMap["location_shop_generic_ddd_01_118"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }, { name = "other", tiles = {"food_02_12", "food_02_20"} }, { name = "other", tiles = {"books&misc_01_76", "books&misc_01_84"} }, { name = "other", tiles = {"books&misc_02_76", "books&misc_02_84"} }}
overlayMap["location_shop_generic_ddd_01_119"] = {{ name = "other", tiles = {"food_01_13", "food_01_21"} }, { name = "other", tiles = {"food_02_13", "food_02_21"} }, { name = "other", tiles = {"books&misc_01_77", "books&misc_01_85"} }, { name = "other", tiles = {"books&misc_02_77", "books&misc_02_85"} }}
overlayMap["location_shop_generic_ddd_02_0"] = {{ name = "other", tiles = {"clothing_02_8", "clothing_02_16"} }, { name = "other", tiles = {"clothing_01_8", "clothing_01_16"} }}
overlayMap["location_shop_generic_ddd_02_1"] = {{ name = "other", tiles = {"clothing_02_9", "clothing_02_17"} }, { name = "other", tiles = {"clothing_01_9", "clothing_01_17"} }}
overlayMap["location_shop_generic_ddd_02_2"] = {{ name = "other", tiles = {"clothing_02_10", "clothing_02_18"} }, { name = "other", tiles = {"clothing_01_10", "clothing_01_18"} }}
overlayMap["location_shop_generic_ddd_02_5"] = {{ name = "other", tiles = {"clothing_02_11", "clothing_02_19"} }, { name = "other", tiles = {"clothing_01_11", "clothing_01_19"} }}
overlayMap["location_shop_generic_ddd_02_6"] = {{ name = "other", tiles = {"clothing_02_12", "clothing_02_20"} }, { name = "other", tiles = {"clothing_01_12", "clothing_01_20"} }}
overlayMap["location_shop_generic_ddd_02_7"] = {{ name = "other", tiles = {"clothing_02_13", "clothing_02_21"} }, { name = "other", tiles = {"clothing_01_13", "clothing_01_21"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
