require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'

-- ["KitchenBook"]
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalRed");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalOrange");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalYellow");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalGreen");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBlue");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalPurple");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, "TJM.TJMJournalWhite");
table.insert(ProceduralDistributions["list"]["KitchenBook"].items, 4);

-- ["LivingRoomShelf"]
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalRed");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalOrange");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalYellow");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalGreen");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBlue");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalPurple");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, "TJM.TJMJournalWhite");
table.insert(ProceduralDistributions["list"]["LivingRoomShelf"].items, 4);

-- ["ShelfGeneric]
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalRed");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalOrange");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalYellow");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalGreen");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBlue");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalPurple");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, "TJM.TJMJournalWhite");
table.insert(ProceduralDistributions["list"]["ShelfGeneric"].items, 4);

-- ["LivingRoomShelfNoTapes"]
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalRed");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalOrange");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalYellow");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalGreen");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBlue");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalPurple");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBrown");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalBlack");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, "TJM.TJMJournalWhite");
table.insert(ProceduralDistributions["list"]["LivingRoomShelfNoTapes"].items, 4);