-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["LC_Bookstore_12"] = {{ name = "other", tiles = {"LC_Bookstore_8", "LC_Bookstore_10"} }}
overlayMap["LC_Bookstore_13"] = {{ name = "other", tiles = {"LC_Bookstore_9", "LC_Bookstore_11"} }}
overlayMap["LC_Bookstore_14"] = {{ name = "other", tiles = {"LC_Bookstore_18", "LC_Bookstore_16"} }}
overlayMap["LC_Bookstore_15"] = {{ name = "other", tiles = {"LC_Bookstore_19", "LC_Bookstore_17"} }}
overlayMap["LC_Bookstore_26"] = {{ name = "other", tiles = {"LC_Bookstore_24", "LC_Bookstore_24"} }}
overlayMap["LC_Bookstore_27"] = {{ name = "other", tiles = {"LC_Bookstore_25", "LC_Bookstore_25"} }}
overlayMap["LC_Bookstore_30"] = {{ name = "other", tiles = {"LC_Bookstore_28", "LC_Bookstore_28"} }}
overlayMap["LC_Bookstore_31"] = {{ name = "other", tiles = {"LC_Bookstore_29", "LC_Bookstore_29"} }}
overlayMap["LC_Bookstore_38"] = {{ name = "other", tiles = {"LC_Bookstore_28", "LC_Bookstore_28"} }}
overlayMap["LC_Bookstore_39"] = {{ name = "other", tiles = {"LC_Bookstore_29", "LC_Bookstore_29"} }}
overlayMap["LC_Bookstore_42"] = {{ name = "other", tiles = {"LC_Bookstore_40", "LC_Bookstore_40"} }}
overlayMap["LC_Bookstore_43"] = {{ name = "other", tiles = {"LC_Bookstore_41", "LC_Bookstore_41"} }}
overlayMap["LC_Bookstore_44"] = {{ name = "other", tiles = {"LC_Bookstore_48", "LC_Bookstore_52"} }}
overlayMap["LC_Bookstore_45"] = {{ name = "other", tiles = {"LC_Bookstore_49", "LC_Bookstore_53"} }}
overlayMap["LC_Bookstore_46"] = {{ name = "other", tiles = {"LC_Bookstore_50", "LC_Bookstore_54"} }}
overlayMap["LC_Bookstore_47"] = {{ name = "other", tiles = {"LC_Bookstore_51", "LC_Bookstore_55"} }}
overlayMap["LC_Bookstore_60"] = {{ name = "other", tiles = {"LC_Bookstore_56", "LC_Bookstore_58"} }}
overlayMap["LC_Bookstore_61"] = {{ name = "other", tiles = {"LC_Bookstore_57", "LC_Bookstore_59"} }}
overlayMap["LC_Random2_12"] = {{ name = "other", tiles = {"LC_Random2_11", "LC_Random2_11"} }}
overlayMap["LC_Random2_13"] = {{ name = "other", tiles = {"LC_Random2_10", "LC_Random2_10"} }}
overlayMap["LC_Random4_36"] = {{ name = "other", tiles = {"LC_Random4_64", "LC_Random4_39"} }}
overlayMap["LC_Random4_37"] = {{ name = "other", tiles = {"LC_Random4_65", "LC_Random4_38"} }}
overlayMap["LC_Random_42"] = {{ name = "other", tiles = {"LC_Random_46", "LC_Random_46"} }}
overlayMap["LC_Random_44"] = {{ name = "other", tiles = {"LC_Random_45", "LC_Random_45"} }}
overlayMap["LC_VHSstore_0"] = {{ name = "other", tiles = {"LC_VHSstore_8", "LC_VHSstore_12"} }}
overlayMap["LC_VHSstore_1"] = {{ name = "other", tiles = {"LC_VHSstore_9", "LC_VHSstore_9"} }}
overlayMap["LC_VHSstore_2"] = {{ name = "other", tiles = {"LC_VHSstore_10", "LC_VHSstore_14"} }}
overlayMap["LC_VHSstore_3"] = {{ name = "other", tiles = {"LC_VHSstore_11", "LC_VHSstore_15"} }}
overlayMap["LC_VHSstore_40"] = {{ name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["LC_VHSstore_41"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["LC_VHSstore_42"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["LC_VHSstore_43"] = {{ name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["LC_VHSstore_44"] = {{ name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["LC_VHSstore_45"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["LC_VHSstore_46"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["LC_VHSstore_47"] = {{ name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["LC_VHSstore_60"] = {{ name = "other", tiles = {"LC_VHSstore_57", "LC_VHSstore_57"} }}
overlayMap["LC_VHSstore_61"] = {{ name = "other", tiles = {"LC_VHSstore_56", "LC_VHSstore_56"} }}
overlayMap["LC_VHSstore_62"] = {{ name = "other", tiles = {"LC_VHSstore_58", "LC_VHSstore_58"} }}
overlayMap["LC_VHSstore_63"] = {{ name = "other", tiles = {"LC_VHSstore_59", "LC_VHSstore_59"} }}
overlayMap["LC_beach_71"] = {{ name = "other", tiles = {"LC_beach_72", "LC_beach_72"} }}
overlayMap["LC_beach_73"] = {{ name = "other", tiles = {"LC_beach_74", "LC_beach_74"} }}
overlayMap["LC_bedroom1_16"] = {{ name = "other", tiles = {"LC_bedroom1_18", "LC_bedroom1_18"} }}
overlayMap["LC_bedroom1_17"] = {{ name = "other", tiles = {"LC_bedroom1_19", "LC_bedroom1_19"} }}
overlayMap["LC_bedroom1_20"] = {{ name = "other", tiles = {"LC_bedroom1_22", "LC_bedroom1_22"} }}
overlayMap["LC_bedroom1_21"] = {{ name = "other", tiles = {"LC_bedroom1_23", "LC_bedroom1_23"} }}
overlayMap["LC_city_decoration_16"] = {{ name = "other", tiles = {"LC_city_decoration_18", "LC_city_decoration_18"} }}
overlayMap["LC_city_decoration_17"] = {{ name = "other", tiles = {"LC_city_decoration_19", "LC_city_decoration_19"} }}
overlayMap["LC_city_decoration_20"] = {{ name = "other", tiles = {"LC_city_decoration_21", "LC_city_decoration_21"} }}
overlayMap["LC_city_decoration_22"] = {{ name = "other", tiles = {"LC_city_decoration_30", "LC_city_decoration_30"} }}
overlayMap["LC_city_decoration_23"] = {{ name = "other", tiles = {"LC_city_decoration_31", "LC_city_decoration_31"} }}
overlayMap["LC_city_decoration_24"] = {{ name = "other", tiles = {"LC_city_decoration_26", "LC_city_decoration_26"} }}
overlayMap["LC_city_decoration_25"] = {{ name = "other", tiles = {"LC_city_decoration_27", "LC_city_decoration_27"} }}
overlayMap["LC_city_decoration_28"] = {{ name = "other", tiles = {"LC_city_decoration_29", "LC_city_decoration_29"} }}
overlayMap["LC_city_decoration_32"] = {{ name = "other", tiles = {"LC_city_decoration_34", "LC_city_decoration_33"} }}
overlayMap["LC_city_decoration_35"] = {{ name = "other", tiles = {"LC_city_decoration_37", "LC_city_decoration_36"} }}
overlayMap["LC_city_decoration_38"] = {{ name = "other", tiles = {"LC_city_decoration_46", "LC_city_decoration_46"} }}
overlayMap["LC_city_decoration_39"] = {{ name = "other", tiles = {"LC_city_decoration_47", "LC_city_decoration_47"} }}
overlayMap["LC_city_decoration_40"] = {{ name = "other", tiles = {"LC_city_decoration_42", "LC_city_decoration_41"} }}
overlayMap["LC_city_decoration_43"] = {{ name = "other", tiles = {"LC_city_decoration_45", "LC_city_decoration_44"} }}
overlayMap["LC_specific_containers_0"] = {{ name = "other", tiles = {"LC_specific_containers_4", "LC_specific_containers_4"} }}
overlayMap["LC_specific_containers_1"] = {{ name = "other", tiles = {"LC_specific_containers_5", "LC_specific_containers_5"} }}
overlayMap["LC_specific_containers_26"] = {{ name = "other", tiles = {"food_02_96", "food_02_100"} }}
overlayMap["LC_specific_containers_27"] = {{ name = "other", tiles = {"food_02_97", "food_02_101"} }}
overlayMap["LC_specific_containers_28"] = {{ name = "other", tiles = {"food_02_98", "food_02_102"} }}
overlayMap["LC_specific_containers_29"] = {{ name = "other", tiles = {"food_02_99", "food_02_103"} }}
overlayMap["LC_specific_containers_30"] = {{ name = "other", tiles = {"LC_specific_containers_66", "LC_specific_containers_68"} }}
overlayMap["LC_specific_containers_31"] = {{ name = "other", tiles = {"LC_specific_containers_67", "LC_specific_containers_69"} }}
overlayMap["LC_specific_containers_32"] = {{ name = "other", tiles = {"food_02_8", "food_02_16"} }}
overlayMap["LC_specific_containers_33"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["LC_specific_containers_34"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }}
overlayMap["LC_specific_containers_35"] = {{ name = "other", tiles = {"food_02_10", "food_02_18"} }}
overlayMap["LC_specific_containers_36"] = {{ name = "other", tiles = {"food_02_11", "food_02_19"} }}
overlayMap["LC_specific_containers_37"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["LC_specific_containers_38"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }}
overlayMap["LC_specific_containers_39"] = {{ name = "other", tiles = {"food_02_13", "food_02_21"} }}
overlayMap["LC_specific_containers_48"] = {{ name = "other", tiles = {"food_02_64", "food_02_68"} }}
overlayMap["LC_specific_containers_49"] = {{ name = "other", tiles = {"food_02_65", "food_02_69"} }}
overlayMap["LC_specific_containers_50"] = {{ name = "other", tiles = {"food_02_66", "food_02_70"} }}
overlayMap["LC_specific_containers_51"] = {{ name = "other", tiles = {"food_02_67", "food_02_71"} }}
overlayMap["LC_specific_containers_56"] = {{ name = "other", tiles = {"LC_specific_containers_64", "LC_specific_containers_64"} }}
overlayMap["LC_specific_containers_57"] = {{ name = "other", tiles = {"food_02_9", "food_02_17"} }}
overlayMap["LC_specific_containers_58"] = {{ name = "other", tiles = {"food_01_9", "food_01_17"} }}
overlayMap["LC_specific_containers_61"] = {{ name = "other", tiles = {"food_02_12", "food_02_20"} }}
overlayMap["LC_specific_containers_62"] = {{ name = "other", tiles = {"food_01_12", "food_01_20"} }}
overlayMap["LC_specific_containers_63"] = {{ name = "other", tiles = {"LC_specific_containers_65", "LC_specific_containers_65"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
