require 'Items/ProceduralDistributions'
require 'Items/AttachedWeaponDefinitions'

table.insert(ProceduralDistributions["list"]["CrateLumber"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["CrateLumber"].items, 0.4);
table.insert(ProceduralDistributions["list"]["GarageTools"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 0.2);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 3);
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 1);
table.insert(ProceduralDistributions["list"]["GunStoreDisplayCase"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["GunStoreDisplayCase"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 0.8);
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, 0.3);
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, 2);

table.insert(ProceduralDistributions["list"]["CrateLumber"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["CrateLumber"].items, 0.4);
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 0.2);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 3);
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 1);
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 2);
table.insert(ProceduralDistributions["list"]["CrateTools"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["CrateTools"].items, 0.8);
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, 0.3);

table.insert(ProceduralDistributions["list"]["GarageTools"].items, "BCGTools.RancherMachete");
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 0.1);
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, "BCGTools.RancherMachete");
table.insert(ProceduralDistributions["list"]["GigamartTools"].items, 0.5);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.RancherMachete");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 2);
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, "BCGTools.RancherMachete");
table.insert(ProceduralDistributions["list"]["GardenStoreTools"].items, 1);

table.insert(ProceduralDistributions["list"]["GarageTools"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 0.1);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 4);
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 2);
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, 5);
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 4);

table.insert(ProceduralDistributions["list"]["GarageTools"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["GarageTools"].items, 0.05);
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["GunStoreCounter"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreDisplayCase"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["GunStoreDisplayCase"].items, 4);
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 3);
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["PoliceStorageGuns"].items, 2);
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 3);

table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, "BCGTools.KukriMachete");
table.insert(ProceduralDistributions["list"]["ToolStoreTools"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, "BCGTools.KukriMachete");
table.insert(ProceduralDistributions["list"]["GunStoreShelf"].items, 1);
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, "BCGTools.KukriMachete");
table.insert(ProceduralDistributions["list"]["CampingStoreGear"].items, 4);

table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.HandHatchet");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 7);
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.RancherMachete");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 4);
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.SplittingAxe");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 4);
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.KukriMachete");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 6);
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.SurvivalKnife");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 3);
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, "BCGTools.CheapSurvivalKnife");
table.insert(ProceduralDistributions["list"]["MeleeWeapons"].items, 5);